Watching for file changes with StatReloader
Platform is running at risk
C:\Users\JINIT\OneDrive\Desktop\Airline\Airline\settings.py changed, reloading.
INFO Watching for file changes with StatReloader
WARNING Platform is running at risk
INFO C:\Users\JINIT\OneDrive\Desktop\Airline\Airline\settings.py changed, reloading.
django.utils.autoreload INFO 2022-09-13 09:44:35,906 autoreload 58340 61680 Watching for file changes with StatReloader
theme.views.category WARNING 2022-09-13 09:45:38,452 category 58340 70176 Platform is running at risk
theme.views.category WARNING 2022-09-13 09:45:54,129 category 58340 39892 Platform is running at risk
theme.views.category WARNING 2022-09-13 09:57:56,355 category 58340 63904 Platform is running at risk
theme.views.category WARNING 2022-09-13 10:05:36,086 category 58340 67940 Platform is running at risk
theme.views.category WARNING 2022-09-13 10:06:52,162 category 58340 68908 Platform is running at risk
theme.views.category WARNING 2022-09-13 10:07:59,724 category 58340 68068 Platform is running at risk
theme.views.category WARNING 2022-09-13 10:16:08,615 category 58340 72860 Platform is running at risk
theme.views.category WARNING 2022-09-13 10:35:16,179 category 58340 68276 Platform is running at risk
theme.views.category WARNING 2022-09-13 10:36:45,552 category 58340 76704 Platform is running at risk
theme.views.category WARNING 2022-09-13 10:38:51,099 category 58340 61620 Platform is running at risk
django.utils.autoreload INFO 2022-09-14 08:24:02,651 autoreload 57996 68216 Watching for file changes with StatReloader
django.utils.autoreload INFO 2022-09-14 08:36:00,983 autoreload 74904 74660 Watching for file changes with StatReloader
django.request WARNING 2022-09-14 08:36:06,675 log 74904 67456 Not Found: /
django.request WARNING 2022-09-14 08:36:07,164 log 74904 67456 Not Found: /favicon.ico
theme.views.category WARNING 2022-09-14 08:36:22,465 category 74904 8480 Platform is running at risk
theme.views.category WARNING 2022-09-14 08:37:36,338 category 74904 75108 Platform is running at risk
django.utils.autoreload INFO 2022-09-14 08:43:50,576 autoreload 72456 61508 Watching for file changes with StatReloader
theme.views.category WARNING 2022-09-14 08:44:52,913 category 72456 53420 Platform is running at risk
django.request WARNING 2022-09-14 08:46:42,574 log 72456 76032 Not Found: /favicon.ico
theme.views.category WARNING 2022-09-14 08:46:58,946 category 72456 71668 Platform is running at risk
theme.views.category WARNING 2022-09-14 08:49:24,243 category 72456 77776 Platform is running at risk
theme.views.category WARNING 2022-09-14 08:49:35,762 category 72456 42036 Platform is running at risk
theme.views.category WARNING 2022-09-14 08:49:55,568 category 72456 69304 Platform is running at risk
theme.views.category WARNING 2022-09-14 08:50:46,004 category 72456 44420 Platform is running at risk
django.utils.autoreload INFO 2022-09-14 08:50:50,502 autoreload 72456 61508 C:\Users\JINIT\OneDrive\Desktop\Airline\theme\views\category.py changed, reloading.
django.utils.autoreload INFO 2022-09-14 08:50:51,634 autoreload 68636 77072 Watching for file changes with StatReloader
theme.views.category WARNING 2022-09-14 08:51:03,149 category 68636 76808 Platform is running at risk
django.utils.autoreload INFO 2022-09-14 08:53:54,100 autoreload 68636 77072 C:\Users\JINIT\OneDrive\Desktop\Airline\theme\views\category.py changed, reloading.
django.utils.autoreload INFO 2022-09-14 08:53:54,981 autoreload 79684 53036 Watching for file changes with StatReloader
django.utils.autoreload INFO 2022-09-14 08:53:59,821 autoreload 79684 53036 C:\Users\JINIT\OneDrive\Desktop\Airline\theme\views\category.py changed, reloading.
django.utils.autoreload INFO 2022-09-14 08:54:00,659 autoreload 79064 51960 Watching for file changes with StatReloader
django.utils.autoreload INFO 2022-09-14 08:54:11,936 autoreload 79064 51960 C:\Users\JINIT\OneDrive\Desktop\Airline\theme\views\category.py changed, reloading.
django.utils.autoreload INFO 2022-09-14 08:54:12,746 autoreload 62752 20128 Watching for file changes with StatReloader
django.utils.autoreload INFO 2022-09-14 08:54:31,341 autoreload 67964 63128 Watching for file changes with StatReloader
django.utils.autoreload INFO 2022-09-14 08:54:53,707 autoreload 67964 63128 C:\Users\JINIT\OneDrive\Desktop\Airline\theme\views\category.py changed, reloading.
django.utils.autoreload INFO 2022-09-14 08:54:54,542 autoreload 55232 76060 Watching for file changes with StatReloader
theme.views.category WARNING 2022-09-14 08:55:04,581 category 55232 57576 Platform is running at risk
django.utils.autoreload INFO 2022-09-14 08:56:05,305 autoreload 55232 76060 C:\Users\JINIT\OneDrive\Desktop\Airline\theme\views\category.py changed, reloading.
django.utils.autoreload INFO 2022-09-14 08:56:06,074 autoreload 44012 47336 Watching for file changes with StatReloader
django.utils.autoreload INFO 2022-09-14 08:56:10,119 autoreload 44012 47336 C:\Users\JINIT\OneDrive\Desktop\Airline\theme\views\category.py changed, reloading.
django.utils.autoreload INFO 2022-09-14 08:56:11,141 autoreload 76224 79264 Watching for file changes with StatReloader
django.request WARNING 2022-09-14 08:56:54,991 log 76224 30148 Not Found: /demo1/addCategory/index3.html
django.utils.autoreload INFO 2022-09-14 09:00:13,025 autoreload 76224 79264 C:\Users\JINIT\OneDrive\Desktop\Airline\Airline\settings.py changed, reloading.
django.utils.autoreload INFO 2022-09-14 09:00:13,852 autoreload 55636 72392 Watching for file changes with StatReloader
django.utils.autoreload INFO 2022-09-14 09:07:13,632 autoreload 55636 72392 C:\Users\JINIT\OneDrive\Desktop\Airline\Airline\settings.py changed, reloading.
django.utils.autoreload INFO 2022-09-14 09:07:14,905 autoreload 58084 79636 Watching for file changes with StatReloader
django.utils.autoreload INFO 2022-09-14 09:09:00,707 autoreload 58084 79636 C:\Users\JINIT\OneDrive\Desktop\Airline\Airline\settings.py changed, reloading.
django.utils.autoreload INFO 2022-09-14 09:09:01,472 autoreload 79620 51168 Watching for file changes with StatReloader
django.utils.autoreload INFO 2022-09-14 09:22:10,046 autoreload 79620 51168 C:\Users\JINIT\OneDrive\Desktop\Airline\theme\middleware\demoMiddleware.py changed, reloading.
django.utils.autoreload INFO 2022-09-14 09:22:11,576 autoreload 78944 63812 Watching for file changes with StatReloader
django.utils.autoreload INFO 2022-09-14 09:22:47,988 autoreload 78944 63812 C:\Users\JINIT\OneDrive\Desktop\Airline\theme\middleware\demoMiddleware.py changed, reloading.
django.utils.autoreload INFO 2022-09-14 09:22:48,941 autoreload 35248 63412 Watching for file changes with StatReloader
django.utils.autoreload INFO 2022-09-14 09:22:59,234 autoreload 35248 63412 C:\Users\JINIT\OneDrive\Desktop\Airline\theme\middleware\demoMiddleware.py changed, reloading.
django.utils.autoreload INFO 2022-09-14 09:23:00,052 autoreload 74436 80024 Watching for file changes with StatReloader
django.utils.autoreload INFO 2022-09-14 09:38:47,457 autoreload 64544 83784 Watching for file changes with StatReloader
django.utils.autoreload INFO 2022-09-14 09:40:41,549 autoreload 64544 83784 C:\Users\JINIT\OneDrive\Desktop\Airline\Airline\settings.py changed, reloading.
django.utils.autoreload INFO 2022-09-14 09:40:41,809 autoreload 74436 80024 C:\Users\JINIT\OneDrive\Desktop\Airline\Airline\settings.py changed, reloading.
django.utils.autoreload INFO 2022-09-14 09:40:44,555 autoreload 80548 2236 Watching for file changes with StatReloader
django.utils.autoreload INFO 2022-09-14 09:40:47,773 autoreload 73508 81396 Watching for file changes with StatReloader
django.utils.autoreload INFO 2022-09-14 09:42:39,308 autoreload 80548 2236 C:\Users\JINIT\OneDrive\Desktop\Airline\Airline\settings.py changed, reloading.
django.utils.autoreload INFO 2022-09-14 09:42:39,343 autoreload 73508 81396 C:\Users\JINIT\OneDrive\Desktop\Airline\Airline\settings.py changed, reloading.
django.utils.autoreload INFO 2022-09-14 09:42:41,798 autoreload 82284 19624 Watching for file changes with StatReloader
django.utils.autoreload INFO 2022-09-14 09:42:41,876 autoreload 82292 69028 Watching for file changes with StatReloader
theme.middleware.demoMiddleware WARNING 2022-09-14 09:42:50,759 demoMiddleware 82284 73608 Middleware called in new in call
theme.middleware.demoMiddleware WARNING 2022-09-14 09:42:50,864 demoMiddleware 82284 73608 Middleware called in new in call
theme.middleware.demoMiddleware WARNING 2022-09-14 09:42:53,395 demoMiddleware 82284 73608 Middleware called in new in call
theme.views.category WARNING 2022-09-14 09:42:58,732 category 82284 73608 Platform is running at risk
theme.middleware.demoMiddleware WARNING 2022-09-14 09:42:58,734 demoMiddleware 82284 73608 Middleware called in new in call
theme.middleware.demoMiddleware WARNING 2022-09-14 09:42:58,751 demoMiddleware 82284 73608 Middleware called in new in call
django.utils.autoreload INFO 2022-09-14 09:46:09,021 autoreload 80076 83096 Watching for file changes with StatReloader
django.utils.autoreload INFO 2022-09-14 10:20:57,611 autoreload 81616 87080 Watching for file changes with StatReloader
theme.middleware.demoMiddleware WARNING 2022-09-14 10:21:06,470 demoMiddleware 81616 86344 Middleware called in new in call
django.utils.autoreload INFO 2022-09-14 10:22:36,946 autoreload 81616 87080 C:\Users\JINIT\OneDrive\Desktop\Airline\theme\middleware\demoMiddleware.py changed, reloading.
django.utils.autoreload INFO 2022-09-14 10:22:38,766 autoreload 58276 85168 Watching for file changes with StatReloader
django.utils.autoreload INFO 2022-09-14 10:23:15,910 autoreload 58276 85168 C:\Users\JINIT\OneDrive\Desktop\Airline\theme\middleware\demoMiddleware.py changed, reloading.
django.utils.autoreload INFO 2022-09-14 10:23:17,619 autoreload 84932 87436 Watching for file changes with StatReloader
theme.middleware.demoMiddleware WARNING 2022-09-14 10:45:24,973 demoMiddleware 84932 82012 Middleware called in new in call
django.utils.autoreload INFO 2022-09-15 08:33:09,756 autoreload 23524 48848 Watching for file changes with StatReloader
theme.middleware.demoMiddleware WARNING 2022-09-15 08:33:20,849 demoMiddleware 23524 6596 Middleware called in new in call
django.request WARNING 2022-09-15 08:33:20,852 log 23524 6596 Not Found: /
theme.middleware.demoMiddleware WARNING 2022-09-15 08:33:24,536 demoMiddleware 23524 84436 Middleware called in new in call
django.request WARNING 2022-09-15 08:33:24,539 log 23524 84436 Not Found: /favicon.ico
theme.middleware.demoMiddleware WARNING 2022-09-15 08:33:37,219 demoMiddleware 23524 13140 Middleware called in new in call
theme.middleware.demoMiddleware WARNING 2022-09-15 08:33:43,488 demoMiddleware 23524 85140 Middleware called in new in call
theme.middleware.demoMiddleware WARNING 2022-09-15 08:33:46,750 demoMiddleware 23524 54616 Middleware called in new in call
django.utils.autoreload INFO 2022-09-15 08:35:31,857 autoreload 23524 48848 C:\Users\JINIT\OneDrive\Desktop\Airline\theme\migrations\0001_initial.py changed, reloading.
django.utils.autoreload INFO 2022-09-15 08:35:32,999 autoreload 89064 59884 Watching for file changes with StatReloader
django.utils.autoreload INFO 2022-09-15 08:41:25,037 autoreload 89064 59884 C:\Users\JINIT\OneDrive\Desktop\Airline\theme\migrations\0001_initial.py changed, reloading.
django.utils.autoreload INFO 2022-09-15 08:41:25,861 autoreload 6088 13372 Watching for file changes with StatReloader
django.utils.autoreload INFO 2022-09-15 08:42:15,226 autoreload 6088 13372 C:\Users\JINIT\OneDrive\Desktop\Airline\theme\models.py changed, reloading.
django.utils.autoreload INFO 2022-09-15 08:42:16,109 autoreload 84728 82152 Watching for file changes with StatReloader
theme.middleware.demoMiddleware WARNING 2022-09-15 08:42:35,343 demoMiddleware 84728 80988 Middleware called in new in call
django.utils.autoreload INFO 2022-09-15 08:43:24,086 autoreload 84728 82152 C:\Users\JINIT\OneDrive\Desktop\Airline\theme\models.py changed, reloading.
django.utils.autoreload INFO 2022-09-15 08:43:25,054 autoreload 69100 69488 Watching for file changes with StatReloader
django.utils.autoreload INFO 2022-09-15 08:43:45,801 autoreload 69100 69488 C:\Users\JINIT\OneDrive\Desktop\Airline\theme\migrations\0001_initial.py changed, reloading.
django.utils.autoreload INFO 2022-09-15 08:43:46,638 autoreload 85040 64036 Watching for file changes with StatReloader
theme.middleware.demoMiddleware WARNING 2022-09-15 08:48:46,039 demoMiddleware 85040 67164 Middleware called in new in call
django.utils.autoreload INFO 2022-09-15 08:49:13,578 autoreload 85040 64036 C:\Users\JINIT\OneDrive\Desktop\Airline\theme\migrations\0001_initial.py changed, reloading.
django.utils.autoreload INFO 2022-09-15 08:49:14,377 autoreload 77672 64212 Watching for file changes with StatReloader
theme.middleware.demoMiddleware WARNING 2022-09-15 08:49:46,340 demoMiddleware 77672 69664 Middleware called in new in call
django.utils.autoreload INFO 2022-09-15 08:50:06,789 autoreload 77672 64212 C:\Users\JINIT\OneDrive\Desktop\Airline\theme\migrations\0001_initial.py changed, reloading.
django.utils.autoreload INFO 2022-09-15 08:50:07,742 autoreload 79904 68216 Watching for file changes with StatReloader
theme.middleware.demoMiddleware WARNING 2022-09-15 08:50:43,269 demoMiddleware 79904 55804 Middleware called in new in call
theme.middleware.demoMiddleware WARNING 2022-09-15 08:50:50,801 demoMiddleware 79904 68416 Middleware called in new in call
django.utils.autoreload INFO 2022-09-15 08:51:48,334 autoreload 79904 68216 C:\Users\JINIT\OneDrive\Desktop\Airline\theme\models.py changed, reloading.
django.utils.autoreload INFO 2022-09-15 08:51:49,145 autoreload 81388 74500 Watching for file changes with StatReloader
django.utils.autoreload INFO 2022-09-15 08:52:15,208 autoreload 81388 74500 C:\Users\JINIT\OneDrive\Desktop\Airline\theme\models.py changed, reloading.
django.utils.autoreload INFO 2022-09-15 08:52:16,101 autoreload 66612 77356 Watching for file changes with StatReloader
django.utils.autoreload INFO 2022-09-15 08:56:41,231 autoreload 66612 77356 C:\Users\JINIT\OneDrive\Desktop\Airline\theme\models.py changed, reloading.
django.utils.autoreload INFO 2022-09-15 08:56:42,046 autoreload 47068 69108 Watching for file changes with StatReloader
django.utils.autoreload INFO 2022-09-15 08:57:02,052 autoreload 47584 86424 Watching for file changes with StatReloader
django.utils.autoreload INFO 2022-09-15 08:57:35,108 autoreload 84376 41540 Watching for file changes with StatReloader
theme.middleware.demoMiddleware WARNING 2022-09-15 08:57:39,643 demoMiddleware 84376 81404 Middleware called in new in call
theme.middleware.demoMiddleware WARNING 2022-09-15 08:57:46,593 demoMiddleware 84376 83936 Middleware called in new in call
theme.middleware.demoMiddleware WARNING 2022-09-15 08:57:48,924 demoMiddleware 84376 83936 Middleware called in new in call
theme.middleware.demoMiddleware WARNING 2022-09-15 08:57:54,418 demoMiddleware 84376 83936 Middleware called in new in call
django.request ERROR 2022-09-15 08:59:30,798 log 84376 85732 Internal Server Error: /demo1/addCar/
Traceback (most recent call last):
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\JINIT\OneDrive\Desktop\Airline\theme\views\car.py", line 20, in addCar
    return render(request,"car_book/add.html",context)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\backends\django.py", line 62, in render
    return self.template.render(context)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\loader_tags.py", line 132, in render
    compiled_parent = self.get_parent(context)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\loader_tags.py", line 129, in get_parent
    return self.find_template(parent, context)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\loader_tags.py", line 107, in find_template
    template, origin = context.template.engine.find_template(
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 200, in compile_nodelist
    return parser.parse()
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 484, in parse
    raise self.error(token, e)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 482, in parse
    filter_expression = self.compile_filter(token.contents)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 600, in compile_filter
    return FilterExpression(token, self)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 703, in __init__
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: '% url'profile'%' from '% url'profile'%'
theme.middleware.demoMiddleware WARNING 2022-09-15 08:59:30,817 demoMiddleware 84376 85732 Middleware called in new in call
theme.middleware.demoMiddleware WARNING 2022-09-15 08:59:59,929 demoMiddleware 84376 82372 Middleware called in new in call
theme.middleware.demoMiddleware WARNING 2022-09-15 09:00:30,205 demoMiddleware 84376 16588 Middleware called in new in call
theme.middleware.demoMiddleware WARNING 2022-09-15 09:00:30,770 demoMiddleware 84376 16588 Middleware called in new in call
django.request WARNING 2022-09-15 09:00:30,772 log 84376 16588 Not Found: /favicon.ico
django.utils.autoreload INFO 2022-09-15 09:01:21,110 autoreload 84376 41540 C:\Users\JINIT\OneDrive\Desktop\Airline\theme\views\auth.py changed, reloading.
django.utils.autoreload INFO 2022-09-15 09:01:22,086 autoreload 80924 82916 Watching for file changes with StatReloader
theme.middleware.demoMiddleware WARNING 2022-09-15 09:01:32,950 demoMiddleware 80924 88600 Middleware called in new in call
theme.middleware.demoMiddleware WARNING 2022-09-15 09:01:48,269 demoMiddleware 80924 26896 Middleware called in new in call
theme.middleware.demoMiddleware WARNING 2022-09-15 09:02:06,929 demoMiddleware 80924 69008 Middleware called in new in call
theme.middleware.demoMiddleware WARNING 2022-09-15 09:02:20,937 demoMiddleware 80924 88068 Middleware called in new in call
PIL.Image DEBUG 2022-09-15 09:02:47,335 Image 80924 56092 Importing BlpImagePlugin
PIL.Image DEBUG 2022-09-15 09:02:47,339 Image 80924 56092 Importing BmpImagePlugin
PIL.Image DEBUG 2022-09-15 09:02:47,340 Image 80924 56092 Importing BufrStubImagePlugin
PIL.Image DEBUG 2022-09-15 09:02:47,342 Image 80924 56092 Importing CurImagePlugin
PIL.Image DEBUG 2022-09-15 09:02:47,344 Image 80924 56092 Importing DcxImagePlugin
PIL.Image DEBUG 2022-09-15 09:02:47,348 Image 80924 56092 Importing DdsImagePlugin
PIL.Image DEBUG 2022-09-15 09:02:47,350 Image 80924 56092 Importing EpsImagePlugin
PIL.Image DEBUG 2022-09-15 09:02:47,381 Image 80924 56092 Importing FitsImagePlugin
PIL.Image DEBUG 2022-09-15 09:02:47,383 Image 80924 56092 Importing FitsStubImagePlugin
PIL.Image DEBUG 2022-09-15 09:02:47,386 Image 80924 56092 Importing FliImagePlugin
PIL.Image DEBUG 2022-09-15 09:02:47,388 Image 80924 56092 Importing FpxImagePlugin
PIL.Image DEBUG 2022-09-15 09:02:47,390 Image 80924 56092 Image: failed to import FpxImagePlugin: No module named 'olefile'
PIL.Image DEBUG 2022-09-15 09:02:47,390 Image 80924 56092 Importing FtexImagePlugin
PIL.Image DEBUG 2022-09-15 09:02:47,392 Image 80924 56092 Importing GbrImagePlugin
PIL.Image DEBUG 2022-09-15 09:02:47,393 Image 80924 56092 Importing GifImagePlugin
PIL.Image DEBUG 2022-09-15 09:02:47,393 Image 80924 56092 Importing GribStubImagePlugin
PIL.Image DEBUG 2022-09-15 09:02:47,394 Image 80924 56092 Importing Hdf5StubImagePlugin
PIL.Image DEBUG 2022-09-15 09:02:47,396 Image 80924 56092 Importing IcnsImagePlugin
PIL.Image DEBUG 2022-09-15 09:02:47,400 Image 80924 56092 Importing IcoImagePlugin
PIL.Image DEBUG 2022-09-15 09:02:47,402 Image 80924 56092 Importing ImImagePlugin
PIL.Image DEBUG 2022-09-15 09:02:47,405 Image 80924 56092 Importing ImtImagePlugin
PIL.Image DEBUG 2022-09-15 09:02:47,410 Image 80924 56092 Importing IptcImagePlugin
PIL.Image DEBUG 2022-09-15 09:02:47,414 Image 80924 56092 Importing JpegImagePlugin
PIL.Image DEBUG 2022-09-15 09:02:47,414 Image 80924 56092 Importing Jpeg2KImagePlugin
PIL.Image DEBUG 2022-09-15 09:02:47,414 Image 80924 56092 Importing McIdasImagePlugin
PIL.Image DEBUG 2022-09-15 09:02:47,418 Image 80924 56092 Importing MicImagePlugin
PIL.Image DEBUG 2022-09-15 09:02:47,424 Image 80924 56092 Image: failed to import MicImagePlugin: No module named 'olefile'
PIL.Image DEBUG 2022-09-15 09:02:47,424 Image 80924 56092 Importing MpegImagePlugin
PIL.Image DEBUG 2022-09-15 09:02:47,427 Image 80924 56092 Importing MpoImagePlugin
PIL.Image DEBUG 2022-09-15 09:02:47,431 Image 80924 56092 Importing MspImagePlugin
PIL.Image DEBUG 2022-09-15 09:02:47,435 Image 80924 56092 Importing PalmImagePlugin
PIL.Image DEBUG 2022-09-15 09:02:47,442 Image 80924 56092 Importing PcdImagePlugin
PIL.Image DEBUG 2022-09-15 09:02:47,446 Image 80924 56092 Importing PcxImagePlugin
PIL.Image DEBUG 2022-09-15 09:02:47,446 Image 80924 56092 Importing PdfImagePlugin
PIL.Image DEBUG 2022-09-15 09:02:47,465 Image 80924 56092 Importing PixarImagePlugin
PIL.Image DEBUG 2022-09-15 09:02:47,469 Image 80924 56092 Importing PngImagePlugin
PIL.Image DEBUG 2022-09-15 09:02:47,469 Image 80924 56092 Importing PpmImagePlugin
PIL.Image DEBUG 2022-09-15 09:02:47,469 Image 80924 56092 Importing PsdImagePlugin
PIL.Image DEBUG 2022-09-15 09:02:47,473 Image 80924 56092 Importing SgiImagePlugin
PIL.Image DEBUG 2022-09-15 09:02:47,475 Image 80924 56092 Importing SpiderImagePlugin
PIL.Image DEBUG 2022-09-15 09:02:47,477 Image 80924 56092 Importing SunImagePlugin
PIL.Image DEBUG 2022-09-15 09:02:47,479 Image 80924 56092 Importing TgaImagePlugin
PIL.Image DEBUG 2022-09-15 09:02:47,481 Image 80924 56092 Importing TiffImagePlugin
PIL.Image DEBUG 2022-09-15 09:02:47,481 Image 80924 56092 Importing WebPImagePlugin
PIL.Image DEBUG 2022-09-15 09:02:47,587 Image 80924 56092 Importing WmfImagePlugin
PIL.Image DEBUG 2022-09-15 09:02:47,591 Image 80924 56092 Importing XbmImagePlugin
PIL.Image DEBUG 2022-09-15 09:02:47,595 Image 80924 56092 Importing XpmImagePlugin
PIL.Image DEBUG 2022-09-15 09:02:47,599 Image 80924 56092 Importing XVThumbImagePlugin
theme.middleware.demoMiddleware WARNING 2022-09-15 09:02:47,828 demoMiddleware 80924 56092 Middleware called in new in call
theme.middleware.demoMiddleware WARNING 2022-09-15 09:02:47,843 demoMiddleware 80924 56092 Middleware called in new in call
theme.middleware.demoMiddleware WARNING 2022-09-15 09:02:55,835 demoMiddleware 80924 56092 Middleware called in new in call
theme.middleware.demoMiddleware WARNING 2022-09-15 09:02:55,922 demoMiddleware 80924 56092 Middleware called in new in call
theme.middleware.demoMiddleware WARNING 2022-09-15 09:02:56,097 demoMiddleware 80924 43696 Middleware called in new in call
django.request WARNING 2022-09-15 09:02:56,098 log 80924 43696 Not Found: /userProfile/logo.jpeg
theme.middleware.demoMiddleware WARNING 2022-09-15 09:03:10,629 demoMiddleware 80924 85436 Middleware called in new in call
theme.middleware.demoMiddleware WARNING 2022-09-15 09:03:10,683 demoMiddleware 80924 85436 Middleware called in new in call
django.request WARNING 2022-09-15 09:03:10,684 log 80924 85436 Not Found: /userProfile/logo.jpeg
django.utils.autoreload INFO 2022-09-15 09:04:20,855 autoreload 80924 82916 C:\Users\JINIT\OneDrive\Desktop\Airline\theme\views\auth.py changed, reloading.
django.utils.autoreload INFO 2022-09-15 09:04:21,849 autoreload 67448 84304 Watching for file changes with StatReloader
django.request ERROR 2022-09-15 09:16:56,657 log 67448 45460 Internal Server Error: /demo1/Home/
Traceback (most recent call last):
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 505, in parse
    compile_func = self.tags[command]
KeyError: 'static'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\JINIT\OneDrive\Desktop\Airline\theme\views\auth.py", line 7, in index
    return render(request,"index.html")
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 200, in compile_nodelist
    return parser.parse()
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 507, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 568, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 6: 'static'. Did you forget to register or load this tag?
theme.middleware.demoMiddleware WARNING 2022-09-15 09:16:56,681 demoMiddleware 67448 45460 Middleware called in new in call
theme.middleware.demoMiddleware WARNING 2022-09-15 09:17:17,575 demoMiddleware 67448 89156 Middleware called in new in call
theme.middleware.demoMiddleware WARNING 2022-09-15 09:17:18,039 demoMiddleware 67448 83892 Middleware called in new in call
django.request WARNING 2022-09-15 09:17:18,040 log 67448 83892 Not Found: /demo1/Home/images/banner3.jpg
theme.middleware.demoMiddleware WARNING 2022-09-15 09:17:39,252 demoMiddleware 67448 83208 Middleware called in new in call
django.request WARNING 2022-09-15 09:17:39,252 log 67448 83208 Not Found: /demo1/Home/images/banner3.jpg
theme.middleware.demoMiddleware WARNING 2022-09-15 09:17:43,406 demoMiddleware 67448 83208 Middleware called in new in call
theme.middleware.demoMiddleware WARNING 2022-09-15 09:17:55,218 demoMiddleware 67448 89172 Middleware called in new in call
theme.middleware.demoMiddleware WARNING 2022-09-15 09:17:55,239 demoMiddleware 67448 89172 Middleware called in new in call
theme.middleware.demoMiddleware WARNING 2022-09-15 09:17:55,310 demoMiddleware 67448 89172 Middleware called in new in call
django.request WARNING 2022-09-15 09:17:55,311 log 67448 89172 Not Found: /demo1/Home/images/banner3.jpg
theme.middleware.demoMiddleware WARNING 2022-09-15 09:18:07,850 demoMiddleware 67448 4396 Middleware called in new in call
django.request WARNING 2022-09-15 09:18:07,851 log 67448 4396 Not Found: /demo1/Home/images/banner3.jpg
theme.middleware.demoMiddleware WARNING 2022-09-15 09:20:53,852 demoMiddleware 67448 89396 Middleware called in new in call
django.request WARNING 2022-09-15 09:20:53,852 log 67448 89396 Not Found: /demo1/Home/images/banner3.jpg
theme.middleware.demoMiddleware WARNING 2022-09-15 09:22:05,874 demoMiddleware 67448 85816 Middleware called in new in call
django.request WARNING 2022-09-15 09:22:05,875 log 67448 85816 Not Found: /demo1/Home/images/banner3.jpg
django.utils.autoreload INFO 2022-09-15 09:27:17,424 autoreload 92136 92140 Watching for file changes with StatReloader
theme.middleware.demoMiddleware WARNING 2022-09-15 09:27:21,192 demoMiddleware 92136 43208 Middleware called in new in call
theme.middleware.demoMiddleware WARNING 2022-09-15 09:27:21,670 demoMiddleware 92136 43208 Middleware called in new in call
django.request WARNING 2022-09-15 09:27:21,672 log 92136 43208 Not Found: /demo1/Home/images/banner3.jpg
theme.middleware.demoMiddleware WARNING 2022-09-15 09:28:53,758 demoMiddleware 92136 88744 Middleware called in new in call
django.request WARNING 2022-09-15 09:28:53,759 log 92136 88744 Not Found: /demo1/Home/images/banner3.jpg
theme.middleware.demoMiddleware WARNING 2022-09-15 09:30:59,151 demoMiddleware 92136 80880 Middleware called in new in call
theme.middleware.demoMiddleware WARNING 2022-09-15 09:30:59,238 demoMiddleware 92136 80880 Middleware called in new in call
django.request WARNING 2022-09-15 09:30:59,238 log 92136 80880 Not Found: /demo1/Home/images/banner3.jpg
theme.middleware.demoMiddleware WARNING 2022-09-15 09:31:12,868 demoMiddleware 92136 77764 Middleware called in new in call
django.request WARNING 2022-09-15 09:31:12,869 log 92136 77764 Not Found: /demo1/Home/images/banner3.jpg
django.utils.autoreload INFO 2022-09-15 09:32:29,050 autoreload 92136 92140 C:\Users\JINIT\OneDrive\Desktop\Airline\mainApp\urls.py changed, reloading.
django.utils.autoreload INFO 2022-09-15 09:32:30,046 autoreload 90272 90368 Watching for file changes with StatReloader
django.utils.autoreload INFO 2022-09-15 09:32:58,014 autoreload 90272 90368 C:\Users\JINIT\OneDrive\Desktop\Airline\mainApp\views.py changed, reloading.
django.utils.autoreload INFO 2022-09-15 09:32:58,948 autoreload 89736 79072 Watching for file changes with StatReloader
django.utils.autoreload INFO 2022-09-15 09:33:11,097 autoreload 89736 79072 C:\Users\JINIT\OneDrive\Desktop\Airline\mainApp\views.py changed, reloading.
django.utils.autoreload INFO 2022-09-15 09:33:12,180 autoreload 91756 78460 Watching for file changes with StatReloader
django.utils.autoreload INFO 2022-09-15 09:33:25,733 autoreload 91756 78460 C:\Users\JINIT\OneDrive\Desktop\Airline\mainApp\views.py changed, reloading.
django.utils.autoreload INFO 2022-09-15 09:33:26,528 autoreload 78204 68168 Watching for file changes with StatReloader
django.request ERROR 2022-09-15 09:35:39,083 log 78204 91352 Internal Server Error: /demo1/Home/
Traceback (most recent call last):
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\JINIT\OneDrive\Desktop\Airline\theme\views\auth.py", line 7, in index
    return render(request,"index.html")
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\backends\django.py", line 62, in render
    return self.template.render(context)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\defaulttags.py", line 472, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\urls\resolvers.py", line 803, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'book' not found. 'book' is not a valid view function or pattern name.
theme.middleware.demoMiddleware WARNING 2022-09-15 09:35:39,095 demoMiddleware 78204 91352 Middleware called in new in call
theme.middleware.demoMiddleware WARNING 2022-09-15 09:39:20,897 demoMiddleware 78204 65860 Middleware called in new in call
theme.middleware.demoMiddleware WARNING 2022-09-15 09:39:21,032 demoMiddleware 78204 65860 Middleware called in new in call
django.request WARNING 2022-09-15 09:39:21,033 log 78204 65860 Not Found: /userProfile/logo.jpeg
django.request ERROR 2022-09-15 09:46:48,427 log 78204 89688 Internal Server Error: /demo1/Home/
Traceback (most recent call last):
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\JINIT\OneDrive\Desktop\Airline\theme\views\auth.py", line 7, in index
    return render(request,"index.html")
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\backends\django.py", line 62, in render
    return self.template.render(context)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\defaulttags.py", line 472, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\urls\resolvers.py", line 803, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'book' not found. 'book' is not a valid view function or pattern name.
theme.middleware.demoMiddleware WARNING 2022-09-15 09:46:48,442 demoMiddleware 78204 89688 Middleware called in new in call
theme.middleware.demoMiddleware WARNING 2022-09-15 09:46:50,516 demoMiddleware 78204 89688 Middleware called in new in call
django.request ERROR 2022-09-15 09:47:01,617 log 78204 82920 Internal Server Error: /demo1/Home/
Traceback (most recent call last):
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\JINIT\OneDrive\Desktop\Airline\theme\views\auth.py", line 7, in index
    return render(request,"index.html")
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\backends\django.py", line 62, in render
    return self.template.render(context)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\defaulttags.py", line 472, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\urls\resolvers.py", line 803, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'book' not found. 'book' is not a valid view function or pattern name.
theme.middleware.demoMiddleware WARNING 2022-09-15 09:47:01,627 demoMiddleware 78204 82920 Middleware called in new in call
django.utils.autoreload INFO 2022-09-15 09:49:08,039 autoreload 78204 68168 C:\Users\JINIT\OneDrive\Desktop\Airline\mainApp\views.py changed, reloading.
django.utils.autoreload INFO 2022-09-15 09:49:10,860 autoreload 92204 74456 Watching for file changes with StatReloader
django.utils.autoreload INFO 2022-09-15 10:00:12,975 autoreload 76196 89340 Watching for file changes with StatReloader
theme.middleware.demoMiddleware WARNING 2022-09-15 10:00:18,209 demoMiddleware 76196 92108 Middleware called in new in call
theme.middleware.demoMiddleware WARNING 2022-09-15 10:00:18,334 demoMiddleware 76196 92108 Middleware called in new in call
django.request WARNING 2022-09-15 10:00:18,337 log 76196 92108 Not Found: /demo1/Home/images/banner3.jpg
theme.middleware.demoMiddleware WARNING 2022-09-15 10:06:13,417 demoMiddleware 76196 19720 Middleware called in new in call
theme.middleware.demoMiddleware WARNING 2022-09-15 10:06:13,519 demoMiddleware 76196 19720 Middleware called in new in call
django.request WARNING 2022-09-15 10:06:13,520 log 76196 19720 Not Found: /demo1/Home/images/banner3.jpg
theme.middleware.demoMiddleware WARNING 2022-09-15 10:06:26,119 demoMiddleware 76196 91476 Middleware called in new in call
django.request WARNING 2022-09-15 10:06:26,119 log 76196 91476 Not Found: /demo1/Home/images/banner3.jpg
django.utils.autoreload INFO 2022-09-15 10:08:49,429 autoreload 94096 94116 Watching for file changes with StatReloader
django.utils.autoreload INFO 2022-09-15 10:09:10,940 autoreload 93688 90232 Watching for file changes with StatReloader
theme.middleware.demoMiddleware WARNING 2022-09-15 10:16:29,407 demoMiddleware 93688 93852 Middleware called in new in call
theme.middleware.demoMiddleware WARNING 2022-09-15 10:16:29,597 demoMiddleware 93688 93852 Middleware called in new in call
django.request WARNING 2022-09-15 10:16:29,598 log 93688 93852 Not Found: /demo1/Home/images/banner3.jpg
theme.middleware.demoMiddleware WARNING 2022-09-15 10:16:52,565 demoMiddleware 93688 93852 Middleware called in new in call
django.request WARNING 2022-09-15 10:16:52,565 log 93688 93852 Not Found: /demo1/Home/images/banner3.jpg
theme.middleware.demoMiddleware WARNING 2022-09-15 10:16:56,715 demoMiddleware 93688 93852 Middleware called in new in call
theme.middleware.demoMiddleware WARNING 2022-09-15 10:16:56,800 demoMiddleware 93688 93852 Middleware called in new in call
django.request WARNING 2022-09-15 10:16:56,800 log 93688 93852 Not Found: /demo1/Home/images/banner3.jpg
theme.middleware.demoMiddleware WARNING 2022-09-15 10:17:17,918 demoMiddleware 93688 91408 Middleware called in new in call
django.request WARNING 2022-09-15 10:17:17,918 log 93688 91408 Not Found: /demo1/Home/images/banner3.jpg
theme.middleware.demoMiddleware WARNING 2022-09-15 10:18:59,508 demoMiddleware 93688 93820 Middleware called in new in call
django.utils.autoreload INFO 2022-09-15 19:45:01,442 autoreload 90248 48920 Watching for file changes with StatReloader
theme.middleware.demoMiddleware WARNING 2022-09-15 19:45:07,886 demoMiddleware 90248 87124 Middleware called in new in call
django.request WARNING 2022-09-15 19:45:07,886 log 90248 87124 Not Found: /
theme.middleware.demoMiddleware WARNING 2022-09-15 19:45:08,350 demoMiddleware 90248 69364 Middleware called in new in call
django.request WARNING 2022-09-15 19:45:08,350 log 90248 69364 Not Found: /favicon.ico
theme.middleware.demoMiddleware WARNING 2022-09-15 19:45:16,006 demoMiddleware 90248 69364 Middleware called in new in call
django.request ERROR 2022-09-15 19:45:20,918 log 90248 47352 Internal Server Error: /demo1/Book/
Traceback (most recent call last):
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\JINIT\OneDrive\Desktop\Airline\theme\views\auth.py", line 19, in book
    return render(request,"book.html")
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\backends\django.py", line 62, in render
    return self.template.render(context)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\defaulttags.py", line 472, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\urls\resolvers.py", line 803, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for '' not found. '' is not a valid view function or pattern name.
theme.middleware.demoMiddleware WARNING 2022-09-15 19:45:20,948 demoMiddleware 90248 47352 Middleware called in new in call
theme.middleware.demoMiddleware WARNING 2022-09-15 19:46:35,560 demoMiddleware 90248 91120 Middleware called in new in call
theme.middleware.demoMiddleware WARNING 2022-09-15 19:46:35,663 demoMiddleware 90248 87284 Middleware called in new in call
theme.middleware.demoMiddleware WARNING 2022-09-15 19:46:35,663 demoMiddleware 90248 91120 Middleware called in new in call
theme.middleware.demoMiddleware WARNING 2022-09-15 19:46:35,671 demoMiddleware 90248 95128 Middleware called in new in call
django.request WARNING 2022-09-15 19:46:35,663 log 90248 87284 Not Found: /demo1/Book/css/layout.css
django.request WARNING 2022-09-15 19:46:35,671 log 90248 91120 Not Found: /demo1/Book/css/reset.css
theme.middleware.demoMiddleware WARNING 2022-09-15 19:46:35,679 demoMiddleware 90248 51436 Middleware called in new in call
django.request WARNING 2022-09-15 19:46:35,677 log 90248 95128 Not Found: /demo1/Book/css/style.css
theme.middleware.demoMiddleware WARNING 2022-09-15 19:46:35,689 demoMiddleware 90248 87020 Middleware called in new in call
theme.middleware.demoMiddleware WARNING 2022-09-15 19:46:35,697 demoMiddleware 90248 93920 Middleware called in new in call
django.request WARNING 2022-09-15 19:46:35,679 log 90248 51436 Not Found: /demo1/Book/js/cufon-yui.js
django.request WARNING 2022-09-15 19:46:35,697 log 90248 87020 Not Found: /demo1/Book/js/jquery-1.5.2.js
django.request WARNING 2022-09-15 19:46:35,705 log 90248 93920 Not Found: /demo1/Book/js/cufon-replace.js
theme.middleware.demoMiddleware WARNING 2022-09-15 19:46:35,729 demoMiddleware 90248 73132 Middleware called in new in call
django.request WARNING 2022-09-15 19:46:35,729 log 90248 73132 Not Found: /demo1/Book/js/Cabin_400.font.js
theme.middleware.demoMiddleware WARNING 2022-09-15 19:46:35,755 demoMiddleware 90248 91120 Middleware called in new in call
django.request WARNING 2022-09-15 19:46:35,755 log 90248 91120 Not Found: /demo1/Book/js/tabs.js
theme.middleware.demoMiddleware WARNING 2022-09-15 19:46:35,772 demoMiddleware 90248 95128 Middleware called in new in call
theme.middleware.demoMiddleware WARNING 2022-09-15 19:46:35,784 demoMiddleware 90248 51436 Middleware called in new in call
django.request WARNING 2022-09-15 19:46:35,774 log 90248 95128 Not Found: /demo1/Book/js/jquery.jqtransform.js
django.request WARNING 2022-09-15 19:46:35,793 log 90248 51436 Not Found: /demo1/Book/js/jquery.nivo.slider.pack.js
theme.middleware.demoMiddleware WARNING 2022-09-15 19:46:35,810 demoMiddleware 90248 87020 Middleware called in new in call
django.request WARNING 2022-09-15 19:46:35,810 log 90248 87020 Not Found: /demo1/Book/js/atooltip.jquery.js
theme.middleware.demoMiddleware WARNING 2022-09-15 19:46:35,820 demoMiddleware 90248 93920 Middleware called in new in call
django.request WARNING 2022-09-15 19:46:35,821 log 90248 93920 Not Found: /demo1/Book/js/script.js
theme.middleware.demoMiddleware WARNING 2022-09-15 19:46:35,881 demoMiddleware 90248 93920 Middleware called in new in call
theme.middleware.demoMiddleware WARNING 2022-09-15 19:46:35,888 demoMiddleware 90248 87020 Middleware called in new in call
django.request WARNING 2022-09-15 19:46:35,886 log 90248 93920 Not Found: /demo1/Book/images/icon1.jpg
theme.middleware.demoMiddleware WARNING 2022-09-15 19:46:35,893 demoMiddleware 90248 73132 Middleware called in new in call
theme.middleware.demoMiddleware WARNING 2022-09-15 19:46:35,895 demoMiddleware 90248 51436 Middleware called in new in call
django.request WARNING 2022-09-15 19:46:35,894 log 90248 87020 Not Found: /demo1/Book/images/icon2.jpg
django.request WARNING 2022-09-15 19:46:35,895 log 90248 73132 Not Found: /demo1/Book/images/icon6.jpg
theme.middleware.demoMiddleware WARNING 2022-09-15 19:46:35,903 demoMiddleware 90248 91120 Middleware called in new in call
theme.middleware.demoMiddleware WARNING 2022-09-15 19:46:35,914 demoMiddleware 90248 95128 Middleware called in new in call
django.request WARNING 2022-09-15 19:46:35,903 log 90248 51436 Not Found: /demo1/Book/images/icon3.jpg
django.request WARNING 2022-09-15 19:46:35,914 log 90248 91120 Not Found: /demo1/Book/images/icon5.jpg
django.request WARNING 2022-09-15 19:46:35,919 log 90248 95128 Not Found: /demo1/Book/images/icon4.jpg
theme.middleware.demoMiddleware WARNING 2022-09-15 19:47:40,094 demoMiddleware 90248 55712 Middleware called in new in call
django.request ERROR 2022-09-15 19:56:04,985 log 90248 89416 Internal Server Error: /demo1/Book/
Traceback (most recent call last):
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 505, in parse
    compile_func = self.tags[command]
KeyError: 'static'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\JINIT\OneDrive\Desktop\Airline\theme\views\auth.py", line 19, in book
    return render(request,"book.html")
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 200, in compile_nodelist
    return parser.parse()
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 507, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 568, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 7: 'static'. Did you forget to register or load this tag?
theme.middleware.demoMiddleware WARNING 2022-09-15 19:56:05,022 demoMiddleware 90248 89416 Middleware called in new in call
theme.middleware.demoMiddleware WARNING 2022-09-15 19:56:27,537 demoMiddleware 90248 95160 Middleware called in new in call
django.request ERROR 2022-09-15 19:59:43,398 log 90248 96232 Internal Server Error: /demo1/Book/
Traceback (most recent call last):
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 505, in parse
    compile_func = self.tags[command]
KeyError: "'Home'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\JINIT\OneDrive\Desktop\Airline\theme\views\auth.py", line 19, in book
    return render(request,"book.html")
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 200, in compile_nodelist
    return parser.parse()
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 507, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 568, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 33: ''Home''. Did you forget to register or load this tag?
theme.middleware.demoMiddleware WARNING 2022-09-15 19:59:43,403 demoMiddleware 90248 96232 Middleware called in new in call
theme.middleware.demoMiddleware WARNING 2022-09-15 20:00:26,345 demoMiddleware 90248 59544 Middleware called in new in call
theme.middleware.demoMiddleware WARNING 2022-09-15 20:00:29,728 demoMiddleware 90248 59544 Middleware called in new in call
theme.middleware.demoMiddleware WARNING 2022-09-15 20:00:33,870 demoMiddleware 90248 91912 Middleware called in new in call
django.utils.autoreload INFO 2022-09-15 20:04:29,020 autoreload 90248 48920 C:\Users\JINIT\OneDrive\Desktop\Airline\theme\urls\auth.py changed, reloading.
django.utils.autoreload INFO 2022-09-15 20:04:30,716 autoreload 55092 85140 Watching for file changes with StatReloader
django.utils.autoreload INFO 2022-09-15 20:05:15,965 autoreload 55092 85140 C:\Users\JINIT\OneDrive\Desktop\Airline\theme\views\auth.py changed, reloading.
django.utils.autoreload INFO 2022-09-15 20:05:17,517 autoreload 92396 73324 Watching for file changes with StatReloader
django.utils.autoreload INFO 2022-09-15 20:08:36,770 autoreload 53004 60208 Watching for file changes with StatReloader
theme.middleware.demoMiddleware WARNING 2022-09-15 20:08:46,370 demoMiddleware 53004 77704 Middleware called in new in call
theme.middleware.demoMiddleware WARNING 2022-09-15 20:08:48,370 demoMiddleware 53004 77704 Middleware called in new in call
theme.middleware.demoMiddleware WARNING 2022-09-15 20:08:53,707 demoMiddleware 53004 77704 Middleware called in new in call
django.utils.autoreload INFO 2022-09-15 20:09:20,233 autoreload 53004 60208 C:\Users\JINIT\OneDrive\Desktop\Airline\mainApp\urls.py changed, reloading.
django.utils.autoreload INFO 2022-09-15 20:09:21,897 autoreload 96968 74612 Watching for file changes with StatReloader
theme.middleware.demoMiddleware WARNING 2022-09-15 20:09:58,525 demoMiddleware 96968 95240 Middleware called in new in call
django.utils.autoreload INFO 2022-09-15 20:11:28,997 autoreload 96968 74612 C:\Users\JINIT\OneDrive\Desktop\Airline\theme\views\auth.py changed, reloading.
django.utils.autoreload INFO 2022-09-15 20:11:30,271 autoreload 80608 89808 Watching for file changes with StatReloader
django.utils.autoreload INFO 2022-09-15 20:11:36,523 autoreload 80608 89808 C:\Users\JINIT\OneDrive\Desktop\Airline\theme\urls\auth.py changed, reloading.
django.utils.autoreload INFO 2022-09-15 20:11:37,964 autoreload 96504 71172 Watching for file changes with StatReloader
theme.middleware.demoMiddleware WARNING 2022-09-15 20:53:50,549 demoMiddleware 96504 85888 Middleware called in new in call
django.request WARNING 2022-09-15 20:53:50,557 log 96504 85888 Not Found: /demo1/offers/
django.request ERROR 2022-09-15 20:54:05,879 log 96504 90284 Internal Server Error: /demo1/offer/
Traceback (most recent call last):
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\JINIT\OneDrive\Desktop\Airline\theme\views\auth.py", line 19, in book
    return render(request,"book.html")
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\backends\django.py", line 62, in render
    return self.template.render(context)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\defaulttags.py", line 472, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\urls\resolvers.py", line 803, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'Book' not found. 'Book' is not a valid view function or pattern name.
theme.middleware.demoMiddleware WARNING 2022-09-15 20:54:05,912 demoMiddleware 96504 90284 Middleware called in new in call
theme.middleware.demoMiddleware WARNING 2022-09-15 20:54:46,465 demoMiddleware 96504 73904 Middleware called in new in call
theme.middleware.demoMiddleware WARNING 2022-09-15 20:54:49,931 demoMiddleware 96504 91628 Middleware called in new in call
theme.middleware.demoMiddleware WARNING 2022-09-15 20:55:23,249 demoMiddleware 96504 75320 Middleware called in new in call
django.utils.autoreload INFO 2022-09-15 20:56:30,465 autoreload 96504 71172 C:\Users\JINIT\OneDrive\Desktop\Airline\theme\views\auth.py changed, reloading.
django.utils.autoreload INFO 2022-09-15 20:56:31,770 autoreload 77056 82620 Watching for file changes with StatReloader
theme.middleware.demoMiddleware WARNING 2022-09-15 20:57:28,422 demoMiddleware 77056 94796 Middleware called in new in call
theme.middleware.demoMiddleware WARNING 2022-09-15 20:57:29,936 demoMiddleware 77056 94796 Middleware called in new in call
theme.middleware.demoMiddleware WARNING 2022-09-15 20:57:39,328 demoMiddleware 77056 12428 Middleware called in new in call
theme.middleware.demoMiddleware WARNING 2022-09-15 20:57:46,089 demoMiddleware 77056 12428 Middleware called in new in call
django.utils.autoreload INFO 2022-09-15 20:58:44,664 autoreload 87468 48848 Watching for file changes with StatReloader
theme.middleware.demoMiddleware WARNING 2022-09-15 20:58:48,820 demoMiddleware 87468 90436 Middleware called in new in call
theme.middleware.demoMiddleware WARNING 2022-09-15 20:58:50,548 demoMiddleware 87468 90436 Middleware called in new in call
theme.middleware.demoMiddleware WARNING 2022-09-15 20:58:51,870 demoMiddleware 87468 90436 Middleware called in new in call
theme.middleware.demoMiddleware WARNING 2022-09-15 20:58:54,638 demoMiddleware 87468 90436 Middleware called in new in call
theme.middleware.demoMiddleware WARNING 2022-09-15 20:58:55,375 demoMiddleware 87468 90436 Middleware called in new in call
django.request ERROR 2022-09-15 20:59:03,222 log 87468 50632 Internal Server Error: /demo1/Home/
Traceback (most recent call last):
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 505, in parse
    compile_func = self.tags[command]
KeyError: "'Home'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\JINIT\OneDrive\Desktop\Airline\theme\views\auth.py", line 8, in index
    return render(request,"index.html")
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 200, in compile_nodelist
    return parser.parse()
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 507, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 568, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 42: ''Home''. Did you forget to register or load this tag?
theme.middleware.demoMiddleware WARNING 2022-09-15 20:59:03,252 demoMiddleware 87468 50632 Middleware called in new in call
django.request ERROR 2022-09-15 20:59:56,541 log 87468 89016 Internal Server Error: /demo1/Home/
Traceback (most recent call last):
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 505, in parse
    compile_func = self.tags[command]
KeyError: "'Home'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\JINIT\OneDrive\Desktop\Airline\theme\views\auth.py", line 8, in index
    return render(request,"index.html")
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 200, in compile_nodelist
    return parser.parse()
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 507, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 568, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 42: ''Home''. Did you forget to register or load this tag?
theme.middleware.demoMiddleware WARNING 2022-09-15 20:59:56,586 demoMiddleware 87468 89016 Middleware called in new in call
django.request ERROR 2022-09-15 21:01:40,266 log 87468 92248 Internal Server Error: /demo1/Home/
Traceback (most recent call last):
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\JINIT\OneDrive\Desktop\Airline\theme\views\auth.py", line 8, in index
    return render(request,"index.html")
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\backends\django.py", line 62, in render
    return self.template.render(context)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\defaulttags.py", line 472, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\urls\resolvers.py", line 803, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'offers' not found. 'offers' is not a valid view function or pattern name.
theme.middleware.demoMiddleware WARNING 2022-09-15 21:01:40,290 demoMiddleware 87468 92248 Middleware called in new in call
theme.middleware.demoMiddleware WARNING 2022-09-15 21:01:54,050 demoMiddleware 87468 91096 Middleware called in new in call
theme.middleware.demoMiddleware WARNING 2022-09-15 21:02:00,620 demoMiddleware 87468 71152 Middleware called in new in call
theme.middleware.demoMiddleware WARNING 2022-09-15 21:02:03,373 demoMiddleware 87468 71152 Middleware called in new in call
theme.middleware.demoMiddleware WARNING 2022-09-15 21:02:04,719 demoMiddleware 87468 71152 Middleware called in new in call
theme.middleware.demoMiddleware WARNING 2022-09-15 21:02:11,273 demoMiddleware 87468 65940 Middleware called in new in call
theme.middleware.demoMiddleware WARNING 2022-09-15 21:02:12,967 demoMiddleware 87468 65940 Middleware called in new in call
theme.middleware.demoMiddleware WARNING 2022-09-15 21:04:51,775 demoMiddleware 87468 60948 Middleware called in new in call
theme.middleware.demoMiddleware WARNING 2022-09-15 21:04:55,212 demoMiddleware 87468 71416 Middleware called in new in call
theme.middleware.demoMiddleware WARNING 2022-09-15 21:04:57,684 demoMiddleware 87468 71416 Middleware called in new in call
django.utils.autoreload INFO 2022-09-15 21:05:53,852 autoreload 87468 48848 C:\Users\JINIT\OneDrive\Desktop\Airline\theme\urls\auth.py changed, reloading.
django.utils.autoreload INFO 2022-09-15 21:05:55,525 autoreload 54036 91252 Watching for file changes with StatReloader
theme.middleware.demoMiddleware WARNING 2022-09-15 21:05:58,111 demoMiddleware 54036 90548 Middleware called in new in call
django.request ERROR 2022-09-15 21:05:59,515 log 54036 90548 Internal Server Error: /demo1/offer/
Traceback (most recent call last):
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\JINIT\OneDrive\Desktop\Airline\theme\views\auth.py", line 22, in offer
    return render(request,"offers.html")
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\backends\django.py", line 62, in render
    return self.template.render(context)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\defaulttags.py", line 472, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\urls\resolvers.py", line 803, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'Book' not found. 'Book' is not a valid view function or pattern name.
theme.middleware.demoMiddleware WARNING 2022-09-15 21:05:59,530 demoMiddleware 54036 90548 Middleware called in new in call
theme.middleware.demoMiddleware WARNING 2022-09-15 21:06:32,308 demoMiddleware 54036 46072 Middleware called in new in call
theme.middleware.demoMiddleware WARNING 2022-09-15 21:06:45,190 demoMiddleware 54036 52376 Middleware called in new in call
theme.middleware.demoMiddleware WARNING 2022-09-15 21:06:52,139 demoMiddleware 54036 40720 Middleware called in new in call
theme.middleware.demoMiddleware WARNING 2022-09-15 21:06:55,358 demoMiddleware 54036 56120 Middleware called in new in call
django.utils.autoreload INFO 2022-09-15 21:21:15,184 autoreload 54036 91252 C:\Users\JINIT\OneDrive\Desktop\Airline\theme\views\auth.py changed, reloading.
django.utils.autoreload INFO 2022-09-15 21:21:16,759 autoreload 93288 86400 Watching for file changes with StatReloader
django.utils.autoreload INFO 2022-09-15 21:21:36,611 autoreload 93288 86400 C:\Users\JINIT\OneDrive\Desktop\Airline\theme\urls\auth.py changed, reloading.
django.utils.autoreload INFO 2022-09-15 21:21:38,125 autoreload 97304 97316 Watching for file changes with StatReloader
theme.middleware.demoMiddleware WARNING 2022-09-15 21:32:30,884 demoMiddleware 97304 82184 Middleware called in new in call
django.request ERROR 2022-09-15 21:32:34,085 log 97304 82184 Internal Server Error: /demo1/services/
Traceback (most recent call last):
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\JINIT\OneDrive\Desktop\Airline\theme\views\auth.py", line 25, in services
    return render(request,"services.html")
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\backends\django.py", line 62, in render
    return self.template.render(context)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\defaulttags.py", line 472, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\urls\resolvers.py", line 803, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'home' not found. 'home' is not a valid view function or pattern name.
theme.middleware.demoMiddleware WARNING 2022-09-15 21:32:34,118 demoMiddleware 97304 82184 Middleware called in new in call
django.request ERROR 2022-09-15 21:33:15,069 log 97304 91460 Internal Server Error: /demo1/services/
Traceback (most recent call last):
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\JINIT\OneDrive\Desktop\Airline\theme\views\auth.py", line 25, in services
    return render(request,"services.html")
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\backends\django.py", line 62, in render
    return self.template.render(context)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\defaulttags.py", line 472, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\urls\resolvers.py", line 803, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'offers' not found. 'offers' is not a valid view function or pattern name.
theme.middleware.demoMiddleware WARNING 2022-09-15 21:33:15,083 demoMiddleware 97304 91460 Middleware called in new in call
theme.middleware.demoMiddleware WARNING 2022-09-15 21:33:47,676 demoMiddleware 97304 96000 Middleware called in new in call
theme.middleware.demoMiddleware WARNING 2022-09-15 21:33:52,460 demoMiddleware 97304 97140 Middleware called in new in call
theme.middleware.demoMiddleware WARNING 2022-09-15 21:33:53,372 demoMiddleware 97304 97140 Middleware called in new in call
theme.middleware.demoMiddleware WARNING 2022-09-15 21:33:54,695 demoMiddleware 97304 97140 Middleware called in new in call
theme.middleware.demoMiddleware WARNING 2022-09-15 21:33:56,162 demoMiddleware 97304 97140 Middleware called in new in call
django.utils.autoreload INFO 2022-09-15 21:40:25,658 autoreload 97304 97316 C:\Users\JINIT\OneDrive\Desktop\Airline\theme\views\auth.py changed, reloading.
django.utils.autoreload INFO 2022-09-15 21:40:27,244 autoreload 31044 95192 Watching for file changes with StatReloader
django.utils.autoreload INFO 2022-09-15 21:41:07,178 autoreload 31044 95192 C:\Users\JINIT\OneDrive\Desktop\Airline\theme\urls\auth.py changed, reloading.
django.utils.autoreload INFO 2022-09-15 21:41:08,317 autoreload 85020 93416 Watching for file changes with StatReloader
theme.middleware.demoMiddleware WARNING 2022-09-15 21:43:30,165 demoMiddleware 85020 94276 Middleware called in new in call
theme.middleware.demoMiddleware WARNING 2022-09-15 21:43:31,087 demoMiddleware 85020 94276 Middleware called in new in call
django.request WARNING 2022-09-15 21:43:31,087 log 85020 94276 Not Found: /demo1/services/safety.html
theme.middleware.demoMiddleware WARNING 2022-09-15 21:44:08,737 demoMiddleware 85020 94276 Middleware called in new in call
django.request WARNING 2022-09-15 21:44:08,737 log 85020 94276 Not Found: /demo1/services/safety.html
theme.middleware.demoMiddleware WARNING 2022-09-15 21:44:14,564 demoMiddleware 85020 94276 Middleware called in new in call
django.request WARNING 2022-09-15 21:44:14,564 log 85020 94276 Not Found: /demo1/services/safety.html
theme.middleware.demoMiddleware WARNING 2022-09-15 21:45:19,828 demoMiddleware 85020 85824 Middleware called in new in call
django.request WARNING 2022-09-15 21:45:19,830 log 85020 85824 Not Found: /demo1/services/safety.html
django.utils.autoreload INFO 2022-09-15 21:45:34,298 autoreload 85020 93416 C:\Users\JINIT\OneDrive\Desktop\Airline\theme\urls\auth.py changed, reloading.
django.utils.autoreload INFO 2022-09-15 21:45:35,668 autoreload 85024 77512 Watching for file changes with StatReloader
theme.middleware.demoMiddleware WARNING 2022-09-15 21:45:36,197 demoMiddleware 85024 97628 Middleware called in new in call
django.request WARNING 2022-09-15 21:45:36,197 log 85024 97628 Not Found: /demo1/services/safety.html
theme.middleware.demoMiddleware WARNING 2022-09-15 21:45:40,121 demoMiddleware 85024 97628 Middleware called in new in call
django.request ERROR 2022-09-15 21:45:41,126 log 85024 95368 Internal Server Error: /demo1/safety/
Traceback (most recent call last):
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 505, in parse
    compile_func = self.tags[command]
KeyError: 'static'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\JINIT\OneDrive\Desktop\Airline\theme\views\auth.py", line 28, in safety
    return render(request,"safety.html"),
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 200, in compile_nodelist
    return parser.parse()
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 507, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 568, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 6: 'static'. Did you forget to register or load this tag?
theme.middleware.demoMiddleware WARNING 2022-09-15 21:45:41,154 demoMiddleware 85024 95368 Middleware called in new in call
django.request ERROR 2022-09-15 21:46:25,260 log 85024 68156 Internal Server Error: /demo1/safety/
Traceback (most recent call last):
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\JINIT\OneDrive\Desktop\Airline\theme\views\auth.py", line 28, in safety
    return render(request,"safety.html"),
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\backends\django.py", line 62, in render
    return self.template.render(context)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\defaulttags.py", line 472, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\urls\resolvers.py", line 803, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'offers' not found. 'offers' is not a valid view function or pattern name.
theme.middleware.demoMiddleware WARNING 2022-09-15 21:46:25,268 demoMiddleware 85024 68156 Middleware called in new in call
theme.middleware.demoMiddleware WARNING 2022-09-15 21:46:51,134 demoMiddleware 85024 50240 Middleware called in new in call
django.request ERROR 2022-09-15 21:46:51,182 log 85024 50240 Internal Server Error: /demo1/safety/
Traceback (most recent call last):
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\utils\deprecation.py", line 138, in __call__
    response = self.process_response(request, response)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\middleware\clickjacking.py", line 27, in process_response
    if response.get("X-Frame-Options") is not None:
AttributeError: 'tuple' object has no attribute 'get'
django.utils.autoreload INFO 2022-09-15 21:47:35,392 autoreload 85024 77512 C:\Users\JINIT\OneDrive\Desktop\Airline\theme\views\auth.py changed, reloading.
django.utils.autoreload INFO 2022-09-15 21:47:36,741 autoreload 93056 74292 Watching for file changes with StatReloader
theme.middleware.demoMiddleware WARNING 2022-09-15 21:47:37,072 demoMiddleware 93056 53896 Middleware called in new in call
theme.middleware.demoMiddleware WARNING 2022-09-15 21:47:43,282 demoMiddleware 93056 84868 Middleware called in new in call
theme.middleware.demoMiddleware WARNING 2022-09-15 21:47:44,324 demoMiddleware 93056 84868 Middleware called in new in call
theme.middleware.demoMiddleware WARNING 2022-09-15 21:47:45,476 demoMiddleware 93056 84868 Middleware called in new in call
theme.middleware.demoMiddleware WARNING 2022-09-15 21:48:04,150 demoMiddleware 93056 92220 Middleware called in new in call
theme.middleware.demoMiddleware WARNING 2022-09-15 21:48:05,088 demoMiddleware 93056 92220 Middleware called in new in call
django.request WARNING 2022-09-15 21:48:05,089 log 93056 92220 Not Found: /favicon.ico
theme.middleware.demoMiddleware WARNING 2022-09-15 21:48:11,234 demoMiddleware 93056 94244 Middleware called in new in call
theme.middleware.demoMiddleware WARNING 2022-09-15 21:48:11,268 demoMiddleware 93056 94244 Middleware called in new in call
theme.middleware.demoMiddleware WARNING 2022-09-15 21:48:17,531 demoMiddleware 93056 94244 Middleware called in new in call
theme.middleware.demoMiddleware WARNING 2022-09-15 21:48:21,518 demoMiddleware 93056 94244 Middleware called in new in call
theme.middleware.demoMiddleware WARNING 2022-09-15 21:48:28,147 demoMiddleware 93056 54520 Middleware called in new in call
theme.middleware.demoMiddleware WARNING 2022-09-15 21:48:30,042 demoMiddleware 93056 54520 Middleware called in new in call
theme.middleware.demoMiddleware WARNING 2022-09-15 21:48:30,910 demoMiddleware 93056 54520 Middleware called in new in call
django.utils.autoreload INFO 2022-09-15 21:52:43,258 autoreload 93056 74292 C:\Users\JINIT\OneDrive\Desktop\Airline\theme\views\auth.py changed, reloading.
django.utils.autoreload INFO 2022-09-15 21:52:44,333 autoreload 97804 97844 Watching for file changes with StatReloader
django.utils.autoreload INFO 2022-09-15 21:53:07,202 autoreload 97804 97844 C:\Users\JINIT\OneDrive\Desktop\Airline\theme\urls\auth.py changed, reloading.
django.utils.autoreload INFO 2022-09-15 21:53:08,357 autoreload 96500 97364 Watching for file changes with StatReloader
theme.middleware.demoMiddleware WARNING 2022-09-15 21:55:11,157 demoMiddleware 96500 66932 Middleware called in new in call
django.request ERROR 2022-09-15 21:55:12,431 log 96500 66932 Internal Server Error: /demo1/contacts/
Traceback (most recent call last):
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 505, in parse
    compile_func = self.tags[command]
KeyError: 'static'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\JINIT\OneDrive\Desktop\Airline\theme\views\auth.py", line 31, in contacts
    return render(request,"contacts.html")
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 200, in compile_nodelist
    return parser.parse()
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 507, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 568, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 6: 'static'. Did you forget to register or load this tag?
theme.middleware.demoMiddleware WARNING 2022-09-15 21:55:12,472 demoMiddleware 96500 66932 Middleware called in new in call
theme.middleware.demoMiddleware WARNING 2022-09-15 21:55:31,907 demoMiddleware 96500 93680 Middleware called in new in call
theme.middleware.demoMiddleware WARNING 2022-09-15 21:55:36,937 demoMiddleware 96500 91660 Middleware called in new in call
theme.middleware.demoMiddleware WARNING 2022-09-15 21:55:37,552 demoMiddleware 96500 91660 Middleware called in new in call
theme.middleware.demoMiddleware WARNING 2022-09-15 21:55:38,579 demoMiddleware 96500 91660 Middleware called in new in call
theme.middleware.demoMiddleware WARNING 2022-09-15 21:55:39,344 demoMiddleware 96500 91660 Middleware called in new in call
theme.middleware.demoMiddleware WARNING 2022-09-15 21:55:42,735 demoMiddleware 96500 70832 Middleware called in new in call
theme.middleware.demoMiddleware WARNING 2022-09-15 21:56:24,904 demoMiddleware 96500 97948 Middleware called in new in call
theme.middleware.demoMiddleware WARNING 2022-09-15 21:56:27,304 demoMiddleware 96500 90496 Middleware called in new in call
theme.middleware.demoMiddleware WARNING 2022-09-15 21:56:28,809 demoMiddleware 96500 90496 Middleware called in new in call
theme.middleware.demoMiddleware WARNING 2022-09-15 21:56:29,587 demoMiddleware 96500 90496 Middleware called in new in call
django.request WARNING 2022-09-15 21:56:29,595 log 96500 90496 Not Found: /demo1/safety/contacts.html
theme.middleware.demoMiddleware WARNING 2022-09-15 21:58:42,395 demoMiddleware 96500 92044 Middleware called in new in call
django.request WARNING 2022-09-15 21:58:42,395 log 96500 92044 Not Found: /demo1/safety/contacts.html
theme.middleware.demoMiddleware WARNING 2022-09-15 21:58:47,199 demoMiddleware 96500 59684 Middleware called in new in call
django.request WARNING 2022-09-15 21:58:47,199 log 96500 59684 Not Found: /demo1/safety/contacts.html
django.utils.autoreload INFO 2022-09-15 21:59:16,863 autoreload 94028 98112 Watching for file changes with StatReloader
theme.middleware.demoMiddleware WARNING 2022-09-15 21:59:18,753 demoMiddleware 94028 97344 Middleware called in new in call
django.request WARNING 2022-09-15 21:59:18,753 log 94028 97344 Not Found: /demo1/safety/contacts.html
theme.middleware.demoMiddleware WARNING 2022-09-15 21:59:22,909 demoMiddleware 94028 97344 Middleware called in new in call
theme.middleware.demoMiddleware WARNING 2022-09-15 22:00:00,238 demoMiddleware 94028 89988 Middleware called in new in call
theme.middleware.demoMiddleware WARNING 2022-09-15 22:00:02,379 demoMiddleware 94028 89988 Middleware called in new in call
theme.middleware.demoMiddleware WARNING 2022-09-15 22:00:04,550 demoMiddleware 94028 89988 Middleware called in new in call
theme.middleware.demoMiddleware WARNING 2022-09-15 22:00:06,970 demoMiddleware 94028 89988 Middleware called in new in call
theme.middleware.demoMiddleware WARNING 2022-09-15 22:00:08,278 demoMiddleware 94028 94524 Middleware called in new in call
theme.middleware.demoMiddleware WARNING 2022-09-15 22:00:09,792 demoMiddleware 94028 94524 Middleware called in new in call
theme.middleware.demoMiddleware WARNING 2022-09-15 22:00:53,075 demoMiddleware 94028 98068 Middleware called in new in call
theme.middleware.demoMiddleware WARNING 2022-09-15 22:00:54,939 demoMiddleware 94028 98068 Middleware called in new in call
theme.middleware.demoMiddleware WARNING 2022-09-15 22:00:56,728 demoMiddleware 94028 98068 Middleware called in new in call
django.utils.autoreload INFO 2022-09-16 14:09:11,294 autoreload 98760 94528 Watching for file changes with StatReloader
theme.middleware.demoMiddleware WARNING 2022-09-16 14:09:15,242 demoMiddleware 98760 101440 Middleware called in new in call
django.request WARNING 2022-09-16 14:09:15,244 log 98760 101440 Not Found: /
theme.middleware.demoMiddleware WARNING 2022-09-16 14:09:16,360 demoMiddleware 98760 90160 Middleware called in new in call
django.request WARNING 2022-09-16 14:09:16,364 log 98760 90160 Not Found: /favicon.ico
theme.middleware.demoMiddleware WARNING 2022-09-16 14:09:21,362 demoMiddleware 98760 90160 Middleware called in new in call
theme.middleware.demoMiddleware WARNING 2022-09-16 14:09:33,669 demoMiddleware 98760 93564 Middleware called in new in call
theme.middleware.demoMiddleware WARNING 2022-09-16 14:09:35,266 demoMiddleware 98760 93564 Middleware called in new in call
theme.middleware.demoMiddleware WARNING 2022-09-16 14:09:37,132 demoMiddleware 98760 99128 Middleware called in new in call
theme.middleware.demoMiddleware WARNING 2022-09-16 14:09:38,562 demoMiddleware 98760 99128 Middleware called in new in call
theme.middleware.demoMiddleware WARNING 2022-09-16 14:09:39,906 demoMiddleware 98760 99128 Middleware called in new in call
theme.middleware.demoMiddleware WARNING 2022-09-16 14:09:44,460 demoMiddleware 98760 82728 Middleware called in new in call
theme.middleware.demoMiddleware WARNING 2022-09-16 14:09:47,151 demoMiddleware 98760 101408 Middleware called in new in call
theme.middleware.demoMiddleware WARNING 2022-09-16 14:09:49,684 demoMiddleware 98760 101408 Middleware called in new in call
theme.middleware.demoMiddleware WARNING 2022-09-16 14:10:11,428 demoMiddleware 98760 101844 Middleware called in new in call
theme.middleware.demoMiddleware WARNING 2022-09-16 14:10:14,887 demoMiddleware 98760 101844 Middleware called in new in call
theme.middleware.demoMiddleware WARNING 2022-09-16 14:11:06,760 demoMiddleware 98760 100460 Middleware called in new in call
theme.middleware.demoMiddleware WARNING 2022-09-16 14:15:48,230 demoMiddleware 98760 89432 Middleware called in new in call
theme.middleware.demoMiddleware WARNING 2022-09-16 14:15:53,576 demoMiddleware 98760 29616 Middleware called in new in call
theme.middleware.demoMiddleware WARNING 2022-09-16 14:16:28,627 demoMiddleware 98760 102208 Middleware called in new in call
theme.middleware.demoMiddleware WARNING 2022-09-16 14:16:42,033 demoMiddleware 98760 88604 Middleware called in new in call
theme.middleware.demoMiddleware WARNING 2022-09-16 14:19:33,528 demoMiddleware 98760 101440 Middleware called in new in call
theme.middleware.demoMiddleware WARNING 2022-09-16 14:19:42,306 demoMiddleware 98760 90036 Middleware called in new in call
theme.middleware.demoMiddleware WARNING 2022-09-16 14:19:53,541 demoMiddleware 98760 101712 Middleware called in new in call
theme.middleware.demoMiddleware WARNING 2022-09-16 14:19:54,141 demoMiddleware 98760 101712 Middleware called in new in call
django.request WARNING 2022-09-16 14:19:54,143 log 98760 101712 Not Found: /favicon.ico
theme.middleware.demoMiddleware WARNING 2022-09-16 14:20:24,606 demoMiddleware 98760 85492 Middleware called in new in call
theme.middleware.demoMiddleware WARNING 2022-09-16 14:33:00,653 demoMiddleware 98760 102772 Middleware called in new in call
theme.middleware.demoMiddleware WARNING 2022-09-16 14:50:42,197 demoMiddleware 98760 96992 Middleware called in new in call
django.utils.autoreload INFO 2022-09-16 14:51:05,789 autoreload 98760 94528 C:\Users\JINIT\OneDrive\Desktop\Airline\theme\models.py changed, reloading.
django.utils.autoreload INFO 2022-09-16 14:51:08,140 autoreload 102536 89516 Watching for file changes with StatReloader
django.utils.autoreload INFO 2022-09-16 14:54:57,125 autoreload 102536 89516 C:\Users\JINIT\OneDrive\Desktop\Airline\theme\models.py changed, reloading.
django.utils.autoreload INFO 2022-09-16 14:54:59,188 autoreload 94384 75456 Watching for file changes with StatReloader
theme.middleware.demoMiddleware WARNING 2022-09-16 14:58:17,893 demoMiddleware 94384 85824 Middleware called in new in call
theme.middleware.demoMiddleware WARNING 2022-09-16 14:58:36,379 demoMiddleware 94384 85824 Middleware called in new in call
django.request ERROR 2022-09-16 14:58:37,013 log 94384 85824 Internal Server Error: /demo1/viewBooking/
Traceback (most recent call last):
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\JINIT\OneDrive\Desktop\Airline\theme\views\booking.py", line 12, in viewBooking
    return render(request, "booking/view.html",context)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\backends\django.py", line 62, in render
    return self.template.render(context)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\defaulttags.py", line 238, in render
    nodelist.append(node.render_annotated(context))
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\defaulttags.py", line 472, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\urls\resolvers.py", line 803, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'updateBooking' with arguments '('',)' not found. 1 pattern(s) tried: ['demo1/updateBooking/(?P<id>[^/]+)\\Z']
theme.middleware.demoMiddleware WARNING 2022-09-16 14:58:37,116 demoMiddleware 94384 85824 Middleware called in new in call
django.request ERROR 2022-09-16 14:59:24,149 log 94384 85824 Internal Server Error: /demo1/viewBooking/
Traceback (most recent call last):
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\JINIT\OneDrive\Desktop\Airline\theme\views\booking.py", line 12, in viewBooking
    return render(request, "booking/view.html",context)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\backends\django.py", line 62, in render
    return self.template.render(context)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\defaulttags.py", line 238, in render
    nodelist.append(node.render_annotated(context))
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\defaulttags.py", line 472, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\urls\resolvers.py", line 803, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'updateBooking' with arguments '('',)' not found. 1 pattern(s) tried: ['demo1/updateBooking/(?P<id>[^/]+)\\Z']
theme.middleware.demoMiddleware WARNING 2022-09-16 14:59:24,164 demoMiddleware 94384 85824 Middleware called in new in call
django.request ERROR 2022-09-16 14:59:25,824 log 94384 85824 Internal Server Error: /demo1/viewBooking/
Traceback (most recent call last):
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\JINIT\OneDrive\Desktop\Airline\theme\views\booking.py", line 12, in viewBooking
    return render(request, "booking/view.html",context)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\backends\django.py", line 62, in render
    return self.template.render(context)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\defaulttags.py", line 238, in render
    nodelist.append(node.render_annotated(context))
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\defaulttags.py", line 472, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\urls\resolvers.py", line 803, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'updateBooking' with arguments '('',)' not found. 1 pattern(s) tried: ['demo1/updateBooking/(?P<id>[^/]+)\\Z']
theme.middleware.demoMiddleware WARNING 2022-09-16 14:59:25,882 demoMiddleware 94384 85824 Middleware called in new in call
theme.middleware.demoMiddleware WARNING 2022-09-16 14:59:35,900 demoMiddleware 94384 85824 Middleware called in new in call
theme.middleware.demoMiddleware WARNING 2022-09-16 14:59:52,045 demoMiddleware 94384 82988 Middleware called in new in call
django.request ERROR 2022-09-16 14:59:52,216 log 94384 82988 Internal Server Error: /demo1/viewBooking/
Traceback (most recent call last):
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\JINIT\OneDrive\Desktop\Airline\theme\views\booking.py", line 12, in viewBooking
    return render(request, "booking/view.html",context)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\backends\django.py", line 62, in render
    return self.template.render(context)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\defaulttags.py", line 238, in render
    nodelist.append(node.render_annotated(context))
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\defaulttags.py", line 472, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\urls\resolvers.py", line 803, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'updateBooking' with arguments '('',)' not found. 1 pattern(s) tried: ['demo1/updateBooking/(?P<id>[^/]+)\\Z']
theme.middleware.demoMiddleware WARNING 2022-09-16 14:59:52,246 demoMiddleware 94384 82988 Middleware called in new in call
django.utils.autoreload INFO 2022-09-16 15:01:20,925 autoreload 94384 75456 C:\Users\JINIT\OneDrive\Desktop\Airline\theme\models.py changed, reloading.
django.utils.autoreload INFO 2022-09-16 15:01:23,083 autoreload 101432 94772 Watching for file changes with StatReloader
theme.middleware.demoMiddleware WARNING 2022-09-16 15:01:35,907 demoMiddleware 101432 99816 Middleware called in new in call
theme.middleware.demoMiddleware WARNING 2022-09-16 15:01:44,947 demoMiddleware 101432 99816 Middleware called in new in call
theme.middleware.demoMiddleware WARNING 2022-09-16 15:01:48,308 demoMiddleware 101432 99816 Middleware called in new in call
theme.middleware.demoMiddleware WARNING 2022-09-16 15:01:48,336 demoMiddleware 101432 99816 Middleware called in new in call
theme.middleware.demoMiddleware WARNING 2022-09-16 15:02:01,750 demoMiddleware 101432 99816 Middleware called in new in call
theme.middleware.demoMiddleware WARNING 2022-09-16 15:02:39,106 demoMiddleware 101432 99816 Middleware called in new in call
theme.middleware.demoMiddleware WARNING 2022-09-16 15:02:39,144 demoMiddleware 101432 99816 Middleware called in new in call
theme.middleware.demoMiddleware WARNING 2022-09-16 15:02:46,762 demoMiddleware 101432 99816 Middleware called in new in call
theme.middleware.demoMiddleware WARNING 2022-09-16 15:03:09,751 demoMiddleware 101432 99816 Middleware called in new in call
theme.middleware.demoMiddleware WARNING 2022-09-16 15:03:15,688 demoMiddleware 101432 58780 Middleware called in new in call
theme.middleware.demoMiddleware WARNING 2022-09-16 15:03:15,717 demoMiddleware 101432 58780 Middleware called in new in call
django.utils.autoreload INFO 2022-09-16 15:03:42,555 autoreload 84272 73404 Watching for file changes with StatReloader
theme.middleware.demoMiddleware WARNING 2022-09-16 15:05:29,174 demoMiddleware 84272 84384 Middleware called in new in call
theme.middleware.demoMiddleware WARNING 2022-09-16 15:05:29,247 demoMiddleware 84272 84384 Middleware called in new in call
theme.middleware.demoMiddleware WARNING 2022-09-16 15:05:32,704 demoMiddleware 84272 84384 Middleware called in new in call
theme.middleware.demoMiddleware WARNING 2022-09-16 15:05:45,961 demoMiddleware 84272 77340 Middleware called in new in call
theme.middleware.demoMiddleware WARNING 2022-09-16 15:05:45,991 demoMiddleware 84272 77340 Middleware called in new in call
theme.middleware.demoMiddleware WARNING 2022-09-16 15:05:51,587 demoMiddleware 84272 78580 Middleware called in new in call
theme.middleware.demoMiddleware WARNING 2022-09-16 15:05:53,178 demoMiddleware 84272 78580 Middleware called in new in call
theme.middleware.demoMiddleware WARNING 2022-09-16 15:06:20,407 demoMiddleware 84272 78580 Middleware called in new in call
theme.middleware.demoMiddleware WARNING 2022-09-16 15:06:20,443 demoMiddleware 84272 78580 Middleware called in new in call
django.utils.autoreload INFO 2022-09-16 15:09:50,106 autoreload 104044 58184 Watching for file changes with StatReloader
django.utils.autoreload INFO 2022-09-16 15:13:26,010 autoreload 98612 96412 Watching for file changes with StatReloader
theme.middleware.demoMiddleware WARNING 2022-09-16 15:13:31,084 demoMiddleware 98612 97468 Middleware called in new in call
theme.middleware.demoMiddleware WARNING 2022-09-16 15:13:39,310 demoMiddleware 98612 102676 Middleware called in new in call
theme.middleware.demoMiddleware WARNING 2022-09-16 15:13:52,494 demoMiddleware 98612 100564 Middleware called in new in call
theme.middleware.demoMiddleware WARNING 2022-09-16 15:13:52,529 demoMiddleware 98612 100564 Middleware called in new in call
django.utils.autoreload INFO 2022-09-16 15:34:24,036 autoreload 98612 96412 C:\Users\JINIT\OneDrive\Desktop\Airline\theme\models.py changed, reloading.
django.utils.autoreload INFO 2022-09-16 15:34:26,344 autoreload 73944 91816 Watching for file changes with StatReloader
django.utils.autoreload INFO 2022-09-16 15:35:03,976 autoreload 65500 104084 Watching for file changes with StatReloader
django.utils.autoreload INFO 2022-09-16 15:37:58,893 autoreload 99852 98780 Watching for file changes with StatReloader
django.request ERROR 2022-09-16 15:38:07,988 log 99852 87736 Internal Server Error: /demo1/viewBooking/
Traceback (most recent call last):
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\JINIT\OneDrive\Desktop\Airline\theme\views\booking.py", line 12, in viewBooking
    return render(request, "booking/view.html",context)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\backends\django.py", line 62, in render
    return self.template.render(context)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\defaulttags.py", line 472, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\urls\resolvers.py", line 803, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'addCancel' not found. 'addCancel' is not a valid view function or pattern name.
theme.middleware.demoMiddleware WARNING 2022-09-16 15:38:08,105 demoMiddleware 99852 87736 Middleware called in new in call
django.request ERROR 2022-09-16 15:38:41,713 log 99852 92644 Internal Server Error: /demo1/viewBooking/
Traceback (most recent call last):
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\JINIT\OneDrive\Desktop\Airline\theme\views\booking.py", line 12, in viewBooking
    return render(request, "booking/view.html",context)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\backends\django.py", line 62, in render
    return self.template.render(context)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\defaulttags.py", line 472, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\urls\resolvers.py", line 803, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'addCancel' not found. 'addCancel' is not a valid view function or pattern name.
theme.middleware.demoMiddleware WARNING 2022-09-16 15:38:41,766 demoMiddleware 99852 92644 Middleware called in new in call
django.request ERROR 2022-09-16 15:38:44,233 log 99852 92644 Internal Server Error: /demo1/addBooking/
Traceback (most recent call last):
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\JINIT\OneDrive\Desktop\Airline\theme\views\booking.py", line 21, in addBooking
    return render(request,"booking/add.html",context)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\backends\django.py", line 62, in render
    return self.template.render(context)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\defaulttags.py", line 472, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\urls\resolvers.py", line 803, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'addCancel' not found. 'addCancel' is not a valid view function or pattern name.
theme.middleware.demoMiddleware WARNING 2022-09-16 15:38:44,248 demoMiddleware 99852 92644 Middleware called in new in call
django.request ERROR 2022-09-16 15:38:49,460 log 99852 15544 Internal Server Error: /demo1/viewStatus/
Traceback (most recent call last):
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\JINIT\OneDrive\Desktop\Airline\theme\views\status.py", line 11, in viewStatus
    return render(request, "flight_status/view.html",context)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\backends\django.py", line 62, in render
    return self.template.render(context)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\defaulttags.py", line 472, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\urls\resolvers.py", line 803, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'addCancel' not found. 'addCancel' is not a valid view function or pattern name.
theme.middleware.demoMiddleware WARNING 2022-09-16 15:38:49,499 demoMiddleware 99852 15544 Middleware called in new in call
django.request ERROR 2022-09-16 15:40:50,207 log 99852 95476 Internal Server Error: /demo1/addStatus/
Traceback (most recent call last):
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\JINIT\OneDrive\Desktop\Airline\theme\views\status.py", line 20, in addStatus
    return render(request,"flight_status/add.html",context)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\backends\django.py", line 62, in render
    return self.template.render(context)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\defaulttags.py", line 472, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\urls\resolvers.py", line 803, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'addCancel' not found. 'addCancel' is not a valid view function or pattern name.
theme.middleware.demoMiddleware WARNING 2022-09-16 15:40:50,257 demoMiddleware 99852 95476 Middleware called in new in call
django.request ERROR 2022-09-16 15:40:55,287 log 99852 95476 Internal Server Error: /demo1/viewCategory/
Traceback (most recent call last):
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\JINIT\OneDrive\Desktop\Airline\theme\views\category.py", line 18, in viewCategory
    return render(request, "category/view.html",context)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\backends\django.py", line 62, in render
    return self.template.render(context)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\defaulttags.py", line 472, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\urls\resolvers.py", line 803, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'addCancel' not found. 'addCancel' is not a valid view function or pattern name.
theme.middleware.demoMiddleware WARNING 2022-09-16 15:40:55,316 demoMiddleware 99852 95476 Middleware called in new in call
django.utils.autoreload INFO 2022-09-16 15:41:53,421 autoreload 99852 98780 C:\Users\JINIT\OneDrive\Desktop\Airline\theme\urls\__init__.py changed, reloading.
django.utils.autoreload INFO 2022-09-16 15:41:55,630 autoreload 96536 92348 Watching for file changes with StatReloader
django.utils.autoreload INFO 2022-09-16 15:42:28,209 autoreload 103952 102776 Watching for file changes with StatReloader
django.utils.autoreload INFO 2022-09-16 15:42:45,620 autoreload 103952 102776 C:\Users\JINIT\OneDrive\Desktop\Airline\theme\models.py changed, reloading.
django.utils.autoreload INFO 2022-09-16 15:42:47,804 autoreload 10932 104392 Watching for file changes with StatReloader
theme.middleware.demoMiddleware WARNING 2022-09-16 15:42:48,271 demoMiddleware 10932 59636 Middleware called in new in call
theme.middleware.demoMiddleware WARNING 2022-09-16 15:42:54,286 demoMiddleware 10932 59636 Middleware called in new in call
theme.middleware.demoMiddleware WARNING 2022-09-16 15:43:10,350 demoMiddleware 10932 100020 Middleware called in new in call
theme.middleware.demoMiddleware WARNING 2022-09-16 15:43:10,389 demoMiddleware 10932 100020 Middleware called in new in call
theme.middleware.demoMiddleware WARNING 2022-09-16 16:03:52,548 demoMiddleware 10932 87844 Middleware called in new in call
theme.middleware.demoMiddleware WARNING 2022-09-16 16:03:55,609 demoMiddleware 10932 87844 Middleware called in new in call
theme.middleware.demoMiddleware WARNING 2022-09-16 16:03:58,517 demoMiddleware 10932 103888 Middleware called in new in call
django.request WARNING 2022-09-16 16:03:58,517 log 10932 103888 Not Found: /demo1/deleteCancel/12
theme.middleware.demoMiddleware WARNING 2022-09-16 16:04:38,834 demoMiddleware 10932 99736 Middleware called in new in call
django.request WARNING 2022-09-16 16:04:38,835 log 10932 99736 Not Found: /demo1/deleteCancel
theme.middleware.demoMiddleware WARNING 2022-09-16 16:04:48,350 demoMiddleware 10932 102656 Middleware called in new in call
django.request WARNING 2022-09-16 16:04:48,351 log 10932 102656 Not Found: /demo1/deleteCancel
theme.middleware.demoMiddleware WARNING 2022-09-16 16:04:55,915 demoMiddleware 10932 102656 Middleware called in new in call
theme.middleware.demoMiddleware WARNING 2022-09-16 16:05:00,580 demoMiddleware 10932 98968 Middleware called in new in call
theme.middleware.demoMiddleware WARNING 2022-09-16 16:05:13,502 demoMiddleware 10932 98512 Middleware called in new in call
theme.middleware.demoMiddleware WARNING 2022-09-16 16:05:13,520 demoMiddleware 10932 98512 Middleware called in new in call
django.utils.autoreload INFO 2022-09-16 16:05:47,329 autoreload 10932 104392 C:\Users\JINIT\OneDrive\Desktop\Airline\theme\views\cancel.py changed, reloading.
django.utils.autoreload INFO 2022-09-16 16:05:53,134 autoreload 72804 103256 Watching for file changes with StatReloader
theme.middleware.demoMiddleware WARNING 2022-09-16 16:06:11,561 demoMiddleware 72804 79276 Middleware called in new in call
theme.middleware.demoMiddleware WARNING 2022-09-16 16:06:30,669 demoMiddleware 72804 103052 Middleware called in new in call
theme.middleware.demoMiddleware WARNING 2022-09-16 16:06:38,741 demoMiddleware 72804 101132 Middleware called in new in call
theme.middleware.demoMiddleware WARNING 2022-09-16 16:06:38,770 demoMiddleware 72804 101132 Middleware called in new in call
theme.middleware.demoMiddleware WARNING 2022-09-16 16:06:45,627 demoMiddleware 72804 101132 Middleware called in new in call
theme.middleware.demoMiddleware WARNING 2022-09-16 16:06:50,011 demoMiddleware 72804 104232 Middleware called in new in call
theme.middleware.demoMiddleware WARNING 2022-09-16 16:06:52,359 demoMiddleware 72804 104232 Middleware called in new in call
theme.middleware.demoMiddleware WARNING 2022-09-16 16:07:36,433 demoMiddleware 72804 103916 Middleware called in new in call
theme.middleware.demoMiddleware WARNING 2022-09-16 16:07:36,462 demoMiddleware 72804 103916 Middleware called in new in call
theme.middleware.demoMiddleware WARNING 2022-09-16 16:07:46,815 demoMiddleware 72804 55052 Middleware called in new in call
theme.middleware.demoMiddleware WARNING 2022-09-16 16:09:05,712 demoMiddleware 72804 82040 Middleware called in new in call
theme.middleware.demoMiddleware WARNING 2022-09-16 16:09:05,729 demoMiddleware 72804 82040 Middleware called in new in call
theme.middleware.demoMiddleware WARNING 2022-09-16 16:09:09,656 demoMiddleware 72804 65452 Middleware called in new in call
theme.middleware.demoMiddleware WARNING 2022-09-16 16:09:15,790 demoMiddleware 72804 65452 Middleware called in new in call
theme.middleware.demoMiddleware WARNING 2022-09-16 16:09:15,804 demoMiddleware 72804 65452 Middleware called in new in call
django.utils.autoreload INFO 2022-09-16 16:09:32,734 autoreload 72804 103256 C:\Users\JINIT\OneDrive\Desktop\Airline\theme\views\cancel.py changed, reloading.
django.utils.autoreload INFO 2022-09-16 16:09:33,868 autoreload 99060 101496 Watching for file changes with StatReloader
theme.middleware.demoMiddleware WARNING 2022-09-16 16:09:34,473 demoMiddleware 99060 90056 Middleware called in new in call
theme.middleware.demoMiddleware WARNING 2022-09-16 16:09:37,506 demoMiddleware 99060 90056 Middleware called in new in call
theme.middleware.demoMiddleware WARNING 2022-09-16 16:09:43,238 demoMiddleware 99060 52176 Middleware called in new in call
theme.middleware.demoMiddleware WARNING 2022-09-16 16:09:45,067 demoMiddleware 99060 52176 Middleware called in new in call
theme.middleware.demoMiddleware WARNING 2022-09-16 16:09:52,455 demoMiddleware 99060 99552 Middleware called in new in call
theme.middleware.demoMiddleware WARNING 2022-09-16 16:09:52,468 demoMiddleware 99060 99552 Middleware called in new in call
django.utils.autoreload INFO 2022-09-16 16:10:08,364 autoreload 73500 94844 Watching for file changes with StatReloader
theme.middleware.demoMiddleware WARNING 2022-09-16 16:10:10,368 demoMiddleware 73500 103336 Middleware called in new in call
theme.middleware.demoMiddleware WARNING 2022-09-16 16:10:14,606 demoMiddleware 73500 103336 Middleware called in new in call
theme.middleware.demoMiddleware WARNING 2022-09-16 16:10:36,835 demoMiddleware 73500 103832 Middleware called in new in call
theme.middleware.demoMiddleware WARNING 2022-09-16 16:10:36,855 demoMiddleware 73500 103832 Middleware called in new in call
theme.middleware.demoMiddleware WARNING 2022-09-16 16:11:17,798 demoMiddleware 73500 103080 Middleware called in new in call
theme.middleware.demoMiddleware WARNING 2022-09-16 16:11:22,340 demoMiddleware 73500 103080 Middleware called in new in call
theme.middleware.demoMiddleware WARNING 2022-09-16 16:11:22,355 demoMiddleware 73500 103080 Middleware called in new in call
django.utils.autoreload INFO 2022-09-16 16:12:07,884 autoreload 73500 94844 C:\Users\JINIT\OneDrive\Desktop\Airline\theme\views\cancel.py changed, reloading.
django.utils.autoreload INFO 2022-09-16 16:12:08,927 autoreload 102780 103080 Watching for file changes with StatReloader
theme.middleware.demoMiddleware WARNING 2022-09-16 16:12:13,916 demoMiddleware 102780 99368 Middleware called in new in call
theme.middleware.demoMiddleware WARNING 2022-09-16 16:12:20,783 demoMiddleware 102780 99208 Middleware called in new in call
theme.middleware.demoMiddleware WARNING 2022-09-16 16:12:24,132 demoMiddleware 102780 99208 Middleware called in new in call
theme.middleware.demoMiddleware WARNING 2022-09-16 16:12:28,934 demoMiddleware 102780 28136 Middleware called in new in call
theme.middleware.demoMiddleware WARNING 2022-09-16 16:12:28,964 demoMiddleware 102780 28136 Middleware called in new in call
django.utils.autoreload INFO 2022-09-16 19:45:04,298 autoreload 106452 102832 Watching for file changes with StatReloader
theme.middleware.demoMiddleware WARNING 2022-09-16 19:45:10,903 demoMiddleware 106452 34288 Middleware called in new in call
django.request WARNING 2022-09-16 19:45:10,906 log 106452 34288 Not Found: /
theme.middleware.demoMiddleware WARNING 2022-09-16 19:45:11,363 demoMiddleware 106452 34288 Middleware called in new in call
django.request WARNING 2022-09-16 19:45:11,364 log 106452 34288 Not Found: /favicon.ico
theme.middleware.demoMiddleware WARNING 2022-09-16 19:45:17,908 demoMiddleware 106452 89460 Middleware called in new in call
django.request ERROR 2022-09-16 19:45:23,880 log 106452 100928 Internal Server Error: /demo1/viewCancel/
Traceback (most recent call last):
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\backends\mysql\base.py", line 75, in execute
    return self.cursor.execute(query, args)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\MySQLdb\cursors.py", line 206, in execute
    res = self._query(query)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\MySQLdb\cursors.py", line 319, in _query
    db.query(q)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\MySQLdb\connections.py", line 254, in query
    _mysql.connection.query(self, query)
MySQLdb.OperationalError: (1054, "Unknown column 'theme_cancellationmodel.Booking_id_id' in 'field list'")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\JINIT\OneDrive\Desktop\Airline\theme\views\cancel.py", line 12, in viewCancel
    return render(request, "cancel/view.html",context)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\backends\django.py", line 62, in render
    return self.template.render(context)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\defaulttags.py", line 194, in render
    len_values = len(values)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\query.py", line 376, in __len__
    self._fetch_all()
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\query.py", line 1866, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\query.py", line 87, in __iter__
    results = compiler.execute_sql(
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\sql\compiler.py", line 1395, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\backends\utils.py", line 103, in execute
    return super().execute(sql, params)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\backends\mysql\base.py", line 75, in execute
    return self.cursor.execute(query, args)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\MySQLdb\cursors.py", line 206, in execute
    res = self._query(query)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\MySQLdb\cursors.py", line 319, in _query
    db.query(q)
  File "C:\Users\JINIT\AppData\Local\Programs\Python\Python310\lib\site-packages\MySQLdb\connections.py", line 254, in query
    _mysql.connection.query(self, query)
django.db.utils.OperationalError: (1054, "Unknown column 'theme_cancellationmodel.Booking_id_id' in 'field list'")
theme.middleware.demoMiddleware WARNING 2022-09-16 19:45:23,917 demoMiddleware 106452 100928 Middleware called in new in call
django.utils.autoreload INFO 2022-09-16 19:49:05,011 autoreload 93616 105448 Watching for file changes with StatReloader
theme.middleware.demoMiddleware WARNING 2022-09-16 19:49:09,563 demoMiddleware 93616 104136 Middleware called in new in call
theme.middleware.demoMiddleware WARNING 2022-09-16 19:49:13,724 demoMiddleware 93616 104136 Middleware called in new in call
theme.middleware.demoMiddleware WARNING 2022-09-16 19:49:23,614 demoMiddleware 93616 105984 Middleware called in new in call
theme.middleware.demoMiddleware WARNING 2022-09-16 19:49:37,691 demoMiddleware 93616 101928 Middleware called in new in call
theme.middleware.demoMiddleware WARNING 2022-09-16 19:49:37,732 demoMiddleware 93616 101928 Middleware called in new in call
theme.middleware.demoMiddleware WARNING 2022-09-16 19:49:44,744 demoMiddleware 93616 102008 Middleware called in new in call
theme.middleware.demoMiddleware WARNING 2022-09-16 19:49:48,479 demoMiddleware 93616 102008 Middleware called in new in call
theme.middleware.demoMiddleware WARNING 2022-09-16 19:51:16,557 demoMiddleware 93616 106104 Middleware called in new in call
theme.middleware.demoMiddleware WARNING 2022-09-16 19:51:28,546 demoMiddleware 93616 91588 Middleware called in new in call
theme.middleware.demoMiddleware WARNING 2022-09-16 19:51:29,508 demoMiddleware 93616 91588 Middleware called in new in call
theme.middleware.demoMiddleware WARNING 2022-09-16 19:51:30,660 demoMiddleware 93616 91588 Middleware called in new in call
theme.middleware.demoMiddleware WARNING 2022-09-16 19:51:38,879 demoMiddleware 93616 104416 Middleware called in new in call
theme.middleware.demoMiddleware WARNING 2022-09-16 19:52:07,340 demoMiddleware 93616 98472 Middleware called in new in call
theme.middleware.demoMiddleware WARNING 2022-09-16 19:52:13,335 demoMiddleware 93616 98472 Middleware called in new in call
theme.middleware.demoMiddleware WARNING 2022-09-16 19:52:16,647 demoMiddleware 93616 103732 Middleware called in new in call
django.utils.autoreload INFO 2022-09-16 21:48:36,850 autoreload 93616 105448 C:\Users\JINIT\OneDrive\Desktop\Airline\theme\models.py changed, reloading.
django.utils.autoreload INFO 2022-09-16 21:48:38,698 autoreload 110340 110512 Watching for file changes with StatReloader
django.utils.autoreload INFO 2022-09-16 21:50:46,926 autoreload 110340 110512 C:\Users\JINIT\OneDrive\Desktop\Airline\theme\models.py changed, reloading.
django.utils.autoreload INFO 2022-09-16 21:50:48,505 autoreload 107720 109300 Watching for file changes with StatReloader
django.utils.autoreload INFO 2022-09-16 21:50:59,810 autoreload 107720 109300 C:\Users\JINIT\OneDrive\Desktop\Airline\theme\models.py changed, reloading.
django.utils.autoreload INFO 2022-09-16 21:51:00,943 autoreload 109512 109224 Watching for file changes with StatReloader
theme.middleware.demoMiddleware WARNING 2022-09-16 21:51:16,861 demoMiddleware 109512 83292 Middleware called in new in call
theme.middleware.demoMiddleware WARNING 2022-09-16 21:53:08,492 demoMiddleware 109512 106288 Middleware called in new in call
theme.middleware.demoMiddleware WARNING 2022-09-16 21:53:08,539 demoMiddleware 109512 106288 Middleware called in new in call
theme.middleware.demoMiddleware WARNING 2022-09-16 21:54:18,549 demoMiddleware 109512 103028 Middleware called in new in call
django.utils.autoreload INFO 2022-09-16 23:49:59,256 autoreload 109512 109224 C:\Users\JINIT\OneDrive\Desktop\Airline\theme\urls\__init__.py changed, reloading.
django.utils.autoreload INFO 2022-09-16 23:50:02,298 autoreload 110976 83052 Watching for file changes with StatReloader
django.utils.autoreload INFO 2022-09-16 23:53:36,083 autoreload 110976 83052 C:\Users\JINIT\OneDrive\Desktop\Airline\theme\models.py changed, reloading.
django.utils.autoreload INFO 2022-09-16 23:53:36,991 autoreload 109132 109992 Watching for file changes with StatReloader
django.utils.autoreload INFO 2022-09-16 23:54:15,163 autoreload 109132 109992 C:\Users\JINIT\OneDrive\Desktop\Airline\theme\models.py changed, reloading.
django.utils.autoreload INFO 2022-09-16 23:54:16,168 autoreload 99668 109088 Watching for file changes with StatReloader
theme.middleware.demoMiddleware WARNING 2022-09-16 23:55:02,963 demoMiddleware 99668 108904 Middleware called in new in call
theme.middleware.demoMiddleware WARNING 2022-09-16 23:55:20,892 demoMiddleware 99668 107840 Middleware called in new in call
theme.middleware.demoMiddleware WARNING 2022-09-16 23:55:24,285 demoMiddleware 99668 107840 Middleware called in new in call
django.utils.autoreload INFO 2022-09-16 23:57:01,387 autoreload 107840 109244 Watching for file changes with StatReloader
theme.middleware.demoMiddleware WARNING 2022-09-16 23:57:04,899 demoMiddleware 107840 44512 Middleware called in new in call
theme.middleware.demoMiddleware WARNING 2022-09-16 23:57:05,001 demoMiddleware 107840 44512 Middleware called in new in call
